server.port: 8081

itunes-library-service:
  startup-parsing: true

spring:
  application:
    name: itunes-library-service

  datasource:
    driverClassName: org.h2.Driver
    username: user
    password: pass
    generate-unique-name: false
    url: jdbc:h2:mem:library
#    url: jdbc:h2:file:C:/data/sample

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
#    hibernate.ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /db

logging.level:
  ROOT: INFO
  org.springframework: INFO
  org.hibernate.SQL: INFO
  com.unrec: INFO