server.port: 8081

itunes-library-service:
  startup-parsing: true

spring:
  application:
    name: itunes-library-service

logging.level:
  ROOT: INFO
  org.springframework: INFO
  org.hibernate.SQL: INFO
  com.unrec: INFO

---
spring:
  profiles: dev-h2

  datasource:
    driverClassName: org.h2.Driver
    username: user
    password: pass
    generate-unique-name: false
#    url: jdbc:h2:mem:itunes_library
    url: jdbc:h2:file:C:/data/itunes_library

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: create-drop
    hibernate.ddl-auto: update

  h2:
    console:
      enabled: true
      path: /db
---
spring:
  profiles: dev-pg

  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/itunes_library

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: create-drop
    properties:
      javax.persistence.schema-generation.scripts.action: create
      javax.persistence.schema-generation.scripts.create-target: create.sql
      javax.persistence.schema-generation.scripts.create-source: metadata
      hibernate.format_sql: true