INSERT INTO library.albums (album_name,album_year,compilation,artist_name) VALUES 
('AmeriKKKa''s Most Wanted',1990,NULL,'Ice Cube'),
('Merry Clayton',1971,NULL,'Merry Clayton'),
('Rocks',1976,NULL,'Aerosmith'),
('Next Exit',1992,NULL,'Grover Washington, Jr.'),
('Lion (Original Motion Picture Soundtrack)',2016,true,'VARIOUS_ARTISTS'),
('tgk da best',2010,true,'VARIOUS_ARTISTS'),
('West Kept Secret (The Prequel)',2007,NULL,'Spider Loc'),
('Diamond Life',1984,NULL,'Sade'),
('Export',2014,NULL,'IOWA'),
('Feeling Good - Single',2015,NULL,'Avicii'),
('Everything Not Saved Will Be Lost - Part 2',2019,NULL,'Foals'),
('Doggystyle',1993,NULL,'Snoop Dogg'),
('Three Little Birds - Single',2018,NULL,'Maroon 5'),
('Double Dutchess',2017,true,'VARIOUS_ARTISTS'),
('Rock in a Hard Place',1982,NULL,'Aerosmith'),
('Искусство (EP)',2012,NULL,'Порнофильмы'),
('Come to Me (feat. Nicole Scherzinger) - Single',2006,true,'VARIOUS_ARTISTS'),
('Brother Sister',1994,NULL,'The Brand New Heavies'),
('Furious Angels',2003,NULL,'Rob Dougan'),
('Splinter',2003,NULL,'The Offspring'),
('Illmatic',1994,NULL,'Nas'),
('Sing it Back (CDM)',1999,NULL,'Moloko'),
('Viva La Vida or Death and All His Friends',2008,NULL,'Coldplay'),
('Когда мы вместе, никто не круче',2006,NULL,'Звери'),
('What Went Down',2015,NULL,'Foals'),
('Down 4 Whateva...',1993,NULL,'Nuttin'' Nyce'),
('The Best of Santa Esmeralda',1993,NULL,'Santa Esmeralda'),
('We Remember Sam Cooke',1965,NULL,'The Supremes'),
('Year of the Funky',2017,NULL,'Bei Bei & Shawn Lee'),
('No Time to Die - Single',2020,NULL,'Billie Eilish'),
('Underground Kingz',2007,NULL,'UGK'),
('The Sun Will Come Up, The Seasons Will Change',2019,NULL,'Nina Nesbitt'),
('Rubber Soul',1965,NULL,'The Beatles'),
('Baralku',2017,NULL,'Emancipator'),
('License to Dream',1981,NULL,'Kleeer'),
('Не Париж - Single',2018,NULL,'Ленинград'),
('J.Lo',2001,NULL,'Jennifer Lopez'),
('Nine Lives',1998,NULL,'Aerosmith'),
('Лирика (feat. Masha) - Single',2016,NULL,'Filatov & Karas'),
('Rising Down',2008,NULL,'The Roots'),
('El Dorado',2017,NULL,'Shakira'),
('Страна любви',2003,NULL,'Валерия'),
('I Can''t Stop - Single',2011,NULL,'Flux Pavilion'),
('Русская мечта. Часть 2',2016,NULL,'Порнофильмы'),
('Capitol Punishment',2000,NULL,'Megadeth'),
('Audioslave',2002,NULL,'Audioslave'),
('The Essential Isley Brothers',2004,NULL,'The Isley Brothers'),
('Pictures',2007,NULL,'Katie Melua'),
('In a Low Light',2015,NULL,'Skye'),
('Let''s Get it On',1973,NULL,'Marvin Gaye'),
('Body Talk (Remixes) (EP)',2015,NULL,'Foxes'),
('Restless',2000,NULL,'Xzibit'),
('Scream Aim Fire',2008,NULL,'Bullet for My Valentine'),
('Legion of Boom',2004,NULL,'The Crystal Method'),
('Капиталиzм 00',2000,NULL,'Кирпичи'),
('Bacdafucup',1993,NULL,'Onyx'),
('ununiform',2017,NULL,'Tricky'),
('Sale el Sol',2011,NULL,'Shakira'),
('Hidden Beach Recordings Presents: Unwrapped, Vol. 7',2010,NULL,'Hidden Beach Recordings'),
('Flick of the Switch',1983,NULL,'AC/DC'),
('Godzilla',2003,NULL,'Yukmouth'),
('The Game',2001,NULL,'Richie Rich'),
('The Hits Collection, Volume One',2017,true,'VARIOUS_ARTISTS'),
('PCD',2005,true,'VARIOUS_ARTISTS'),
('Music from Another Dimension!',2012,NULL,'Aerosmith'),
('Beautiful Loser',1975,NULL,'Bob Seger'),
('Look Sharp!',1988,NULL,'Roxette'),
('The Meanest of Times',2007,NULL,'Dropkick Murphys'),
('Songs in A minor',2001,NULL,'Alicia Keys'),
('The Order Of Time',2017,NULL,'Valerie June'),
('Paragon',2015,NULL,'Sabrepulse'),
('Gotta Get a Grip',1990,NULL,'MC Trouble'),
('The Very Best of Fleetwood Mac',2002,NULL,'Fleetwood Mac'),
('Turn Down for What - Single',2013,true,'VARIOUS_ARTISTS'),
('Midnight (Peggy Gou''s After Midnight Mix) - Single',2017,NULL,'Jessie Ware'),
('Angel by the Wings - Single',2016,NULL,'Sia'),
('Rock Steady',2001,NULL,'No Doubt'),
('Malice n Wonderland',2009,NULL,'Snoop Dogg'),
('Booty (feat. Iggy Azalea) - Single',2014,true,'VARIOUS_ARTISTS'),
('Face Value',1981,NULL,'Phil Collins'),
('Rough Dreams',2002,NULL,'Shivaree'),
('Ode to the Ghetto',2008,NULL,'Guilty Simpson'),
('Changes',1982,NULL,'Keni Burke'),
('...Baby One More Time',1999,NULL,'Britney Spears'),
('Naughty''s Nicest',2003,NULL,'Naughty By Nature'),
('True',2013,NULL,'Avicii'),
('Trouble (feat. Jennifer Hudson) - Single',2015,true,'VARIOUS_ARTISTS'),
('Американщина',2006,NULL,'Карандаш'),
('Do or Die',1995,NULL,'Ant Banks'),
('The Dock of the Bay - The Definitive Collection',1992,NULL,'Otis Redding'),
('Jackie Brown Soundtrack',1997,true,'VARIOUS_ARTISTS'),
('Cuban Fire!',1956,NULL,'Stan Kenton'),
('Will Rap For Food',2001,NULL,'CunninLynguists'),
('From Illmatic to Stillmatic: The Remixes EP',2002,NULL,'Nas'),
('A Fistful of Dollars Soundtrack',1964,NULL,'Ennio Morricone'),
('Victim of Love',2013,NULL,'Charles Bradley'),
('Methods of Mayhem',1999,NULL,'Methods of Mayhem'),
('Demolition Soundtrack',2016,true,'VARIOUS_ARTISTS'),
('Kamnesia',2001,NULL,'Kam'),
('From the Muddy Banks of the Wishkah',1996,NULL,'Nirvana'),
('Rhythm of the Night',1985,NULL,'DeBarge'),
('Alive - Single',2018,NULL,'Lil Jon, Offset & 2 Chainz'),
('#1''s',1998,NULL,'Mariah Carey'),
('Show Us Your Hits',2010,NULL,'Bloodhound Gang'),
('Triforce Tunes Level 3',2016,true,'VARIOUS_ARTISTS'),
('The Best',2001,true,'VARIOUS_ARTISTS'),
('Music From the Edge of Heaven',1986,NULL,'Wham!'),
('Fear Itself',1994,NULL,'Casual'),
('Greatest Hits...So Far!!!',2010,NULL,'Pink'),
('Trash World',2018,NULL,'Supercommuter'),
('Expectations - Single',2018,NULL,'Lauren Jauregui'),
('Как ты там - Single',2018,NULL,'ALEKSEEV'),
('Половина камня',2009,NULL,'Jahmal TGK'),
('Planet of the Apes',2004,true,'VARIOUS_ARTISTS'),
('The Man from U.N.C.L.E. Soundtrack',2015,true,'VARIOUS_ARTISTS'),
('Raising Hell',1986,NULL,'Run-D.M.C.'),
('Sakin Ol! (feat. Tuğba Yurt) - Single',2014,NULL,'Doğukan Manço'),
('Acoustic Sessions EP',2010,NULL,'Imany'),
('Hotel California',1976,NULL,'Eagles'),
('Eyes on This',1989,NULL,'MC Lyte'),
('Aria',2000,NULL,'Grover Washington, Jr.'),
('Power of Soul',1974,NULL,'Idris Muhammad'),
('Cosmo''s Factory',1970,NULL,'Creedence Clearwater Revival'),
('The Greatest Hits',1992,NULL,'Nancy Sinatra'),
('Riverside Pictures',1995,NULL,'Walkin'' Large'),
('Endgame',2015,NULL,'Highway Superstar'),
('The Rising Tied',2005,NULL,'Fort Minor'),
('Masters of the Sun Vol. 1',2018,NULL,'Black Eyed Peas'),
('Honeymoon',2015,NULL,'Lana Del Rey'),
('Locked Down',2012,NULL,'Dr. John'),
('The Very Best of Badfinger',2000,NULL,'Badfinger'),
('Star Trek',2009,NULL,'Michael Giacchino'),
('Konvicted',2007,NULL,'Akon'),
('Bleach',1989,NULL,'Nirvana'),
('Fore!',1986,NULL,'Huey Lewis & The News'),
('Yadokari. Kaji Meiko Original Best 12',1973,NULL,'Meiko Kaji'),
('Sen En Guzelsin',2012,NULL,'Yalin'),
('Gluck: Orfeo Ed Euridice',2004,NULL,'Christoph Willibald Gluck'),
('Greatest Hits',1964,NULL,'Mary Wells'),
('Please Please Me',1963,NULL,'The Beatles'),
('Cigarettes After Sex',2017,NULL,'Cigarettes After Sex'),
('In a Soulful Mood',2007,NULL,'Charlie Parker'),
('Made in America',1995,NULL,'Kam'),
('Reload (feat. Konshens) - Single',2019,NULL,'Eve'),
('Abbey Road',1969,NULL,'The Beatles'),
('Tapestry',1971,NULL,'Carole King'),
('Четырёхглавый орёт',2017,NULL,'Каста'),
('Jagged Little Pill',1995,NULL,'Alanis Morissette'),
('Winelight',1980,NULL,'Grover Washington, Jr.'),
('Steal This Album!',2002,NULL,'System of a Down'),
('Who Can Be Trusted?',1992,NULL,'Ray Luv'),
('The Hurra',1995,NULL,'DJ Hurricane'),
('This Land',2019,NULL,'Gary Clark Jr.'),
('Sucker',2014,NULL,'Charli XCX'),
('Hidden Beach Recordings Presents: Unwrapped, Vol. 3',2004,NULL,'Hidden Beach Recordings'),
('Revolver',1966,NULL,'The Beatles'),
('Norman Fucking Rockwell!',2019,NULL,'Lana Del Rey'),
('Corn & Oil',2008,NULL,'American Relay'),
('The Best is Yet to Come',1982,NULL,'Grover Washington, Jr.'),
('Hypnodancer - Single',2020,NULL,'Little Big'),
('<I°_°I>',2015,true,'VARIOUS_ARTISTS'),
('The Beatles (White Album)',1968,NULL,'The Beatles'),
('The Grow Room',2020,NULL,'Richie Rich & The Mekanix'),
('Inside Moves',1984,NULL,'Grover Washington, Jr.'),
('Islander',2014,NULL,'Bernhoft'),
('Judgement Days',2005,NULL,'Ms. Dynamite'),
('Everything Was Beautiful, and Nothing Hurt',2018,NULL,'Moby'),
('Strange Breaks & Mr. Thing',2008,true,'VARIOUS_ARTISTS'),
('Push and Shove',2012,NULL,'No Doubt'),
('Tribes, Vibes and Scribes',1992,NULL,'Incognito'),
('Overtones',2007,NULL,'Just Jack'),
('I Find You Very Attractive',1999,NULL,'Touch and Go'),
('Love and War EP',2015,NULL,'ZZ Ward'),
('The Fharmacist',2001,NULL,'MC Breed'),
('Future Rhythm',1996,NULL,'Digital Underground'),
('Take a Look Around',1990,NULL,'Masta Ace'),
('Exile',2018,NULL,'Sabrepulse'),
('Turmalina',2002,NULL,'Natalia Oreiro'),
('I Got 5 on It (Single)',1995,NULL,'Luniz'),
('Elina Born',2015,NULL,'Elina Born'),
('The Seventh Seal',2009,NULL,'Rakim'),
('Bedtime Stories',1994,NULL,'Madonna'),
('Laundry Service',2002,NULL,'Shakira'),
('G Funk Classics, Vol. 1 & 2',1998,NULL,'Nate Dogg'),
('Pure Heroine',2013,NULL,'Lorde'),
('Yeniden - Single',2015,true,'VARIOUS_ARTISTS'),
('It''s Like That (CDM)',1997,NULL,'Run D.M.C. vs. Jason Nevins'),
('Life is Good',2012,NULL,'Nas'),
('Американщина II',2012,NULL,'Карандаш'),
('Urban Legend',2004,NULL,'T.I.'),
('Наркологический университет миллионов',1997,true,'VARIOUS_ARTISTS'),
('Woodstock',2017,NULL,'Portugal. The Man'),
('Плохо танцевать - Single',2017,NULL,'IOWA'),
('Wasteland, Baby!',2019,NULL,'Hozier'),
('Siren Song - Single',2019,NULL,'MARUV'),
('Use Your Illusion I',1991,NULL,'Guns N'' Roses'),
('Sia: Best Of',2012,true,'VARIOUS_ARTISTS'),
('Mickey Mouse Operation',2006,NULL,'Little People'),
('Showbiz',1999,NULL,'Muse'),
('Босая - Single',2017,NULL,'#2Маши'),
('Archipelago',2012,NULL,'Hidden Orchestra'),
('The Platinum Collection',2007,NULL,'Ennio Morricone'),
('Holy Fire',2013,NULL,'Foals'),
('Спектакль окончен - Single',2013,true,'VARIOUS_ARTISTS'),
('Lyte as a Rock',1988,NULL,'MC Lyte'),
('ROCKISDEAD',2016,NULL,'DOROTHY'),
('5',1998,true,'VARIOUS_ARTISTS'),
('Time Waits for No One - Single',2019,NULL,'Freddie Mercury'),
('Greatest Hits',1998,NULL,'2Pac'),
('Rise - Single',2016,true,'VARIOUS_ARTISTS'),
('Базирование',2014,NULL,'Триагрутрика'),
('The Now Now',2018,NULL,'Gorillaz'),
('Nothing But The Beat',2011,NULL,'David Guetta'),
('Whiplash Soundtrack',2014,true,'VARIOUS_ARTISTS'),
('I Disappear - Single',2000,NULL,'Metallica'),
('Rosenrot',2005,NULL,'Rammstein'),
('Артём расправил плечи',2016,NULL,'Jahmal TGK'),
('We Are Your Friends (CDS)',2006,NULL,'Justice vs. Simian'),
('Lost and Found',2005,NULL,'Will Smith'),
('Tricky Presents Grassroots',1996,true,'VARIOUS_ARTISTS'),
('Bred 2 Die Born 2 Live',2006,NULL,'Lil'' Scrappy'),
('Лучшее 2014',2014,true,'VARIOUS_ARTISTS'),
('Unwrapped Volume 6: Give The Drummer Some!',2009,NULL,'Hidden Beach Recordings'),
('Apollo Kids',2010,NULL,'Ghostface Killah'),
('Melodrama',2017,true,'VARIOUS_ARTISTS'),
('The Affair',2002,NULL,'Easy Access Orchestra'),
('Colour Me Free!',2009,NULL,'Joss Stone'),
('Three Dimensional Ear Pleasure',1995,NULL,'C-Funk'),
('Broken Back',2016,NULL,'Broken Back'),
('The E.N.D.',2009,NULL,'Black Eyed Peas'),
('Picture This',1982,NULL,'Huey Lewis & The News'),
('Всем нашим',2019,NULL,'#2Маши'),
('There Were Seven',2012,NULL,'The Herbaliser'),
('Southernplayalisticadillacmuzik',1994,NULL,'OutKast'),
('Разве ты любил',2016,NULL,'Ани Лорак'),
('Best of Number Ones',2010,NULL,'Janet Jackson'),
('Reise, Reise',2004,NULL,'Rammstein'),
('Planet Rock: The Album',1986,NULL,'Afrika Bambaataa & The Soulsonic Force'),
('Smooth',1995,NULL,'Smooth'),
('Firing Squad',1996,NULL,'M.O.P.'),
('Faithful Man',2012,NULL,'Lee Fields'),
('The New Zapp IV U',1985,NULL,'Zapp'),
('Simple Things',2001,NULL,'Zero 7'),
('Plastic Beach',2010,NULL,'Gorillaz'),
('Out of Business',1999,NULL,'EPMD'),
('Stendhal Syndrome',2012,NULL,'Synapson'),
('Best of Hoobastank',2010,NULL,'Hoobastank'),
('Creep Wit'' Me',1994,NULL,'Ill Al Skratch'),
('The Untouchables Soundtrack',1987,NULL,'Ennio Morricone'),
('Elvis Presley',1956,NULL,'Elvis Presley'),
('2066',2019,NULL,'The Mighty Mocambos'),
('Thank Me Later',2010,NULL,'Drake'),
('Mars',2008,NULL,'Marselle'),
('The Sweet Escape',2006,NULL,'Gwen Stefani'),
('We The People',2006,NULL,'Flipsyde'),
('Surrender',1999,NULL,'The Chemical Brothers'),
('Everythang''s Corrupt - Single',2013,true,'VARIOUS_ARTISTS'),
('Return of the Boom Bap',1993,NULL,'KRS-One'),
('Drones',2015,true,'VARIOUS_ARTISTS'),
('Boston',1976,NULL,'Boston'),
('Последний герой - Single',2019,NULL,'Loboda'),
('Recovery',2010,NULL,'Eminem'),
('Glorious: The Singles 97 - 07',2007,NULL,'Natalie Imbruglia'),
('Talk That Talk',2011,NULL,'Rihanna'),
('11i',2008,NULL,'Supreme Beings of Leisure'),
('Evil Empire',1996,NULL,'Rage Against The Machine'),
('Dusk Till Dawn (feat. Sia) - Single',2017,true,'VARIOUS_ARTISTS'),
('Ain''t No Other',1993,NULL,'MC Lyte'),
('American Idiot',2004,NULL,'Green Day'),
('Shut ''Em Down',1998,NULL,'Onyx'),
('Last Chance, No Breaks',1995,NULL,'Jamal'),
('Unknown Pleasures',1979,NULL,'Joy Division'),
('Head Over Heels',2018,NULL,'Chromeo'),
('Ill Communication',1994,NULL,'Beastie Boys'),
('Berezovskiy',2009,NULL,'АК-47'),
('What the World is Coming To',1976,NULL,'Dexter Wansel'),
('Rock or Bust',2014,NULL,'AC/DC'),
('Blow Your Headphones',1997,NULL,'The Herbaliser'),
('Once in a Blue Moon',1993,NULL,'F-Mob'),
('See Without Eyes',2018,NULL,'The Glitch Mob'),
('All Eyez on Me: Book I',1996,NULL,'2Pac'),
('The R.E.D. Album',2011,NULL,'The Game'),
('Blak and Blu',2012,NULL,'Gary Clark Jr.'),
('London Funk Volume 1',1995,NULL,'London Funk Allstars'),
('Bridges',1977,NULL,'Gil Scott-Heron & Brian Jackson'),
('Лучшее',2011,NULL,'Анна Герман'),
('It''s a Big Daddy Thing',1989,NULL,'Big Daddy Kane'),
('Boomiverse',2017,NULL,'Big Boi'),
('RIVA (Restart the Game) - Single',2015,NULL,'Klingande'),
('Symphony No. 6 "Tragic"',1991,NULL,'Gustav Mahler'),
('Kyou no Wagami wa',1975,NULL,'Meiko Kaji'),
('Gang Related Soundtrack',1997,true,'VARIOUS_ARTISTS'),
('Batucada (CDM)',1998,NULL,'Spiller'),
('Murda Muzik',1999,NULL,'Mobb Deep'),
('All ''N All',1977,NULL,'Earth, Wind & Fire'),
('Liberation',2007,NULL,'Talib Kweli & Madlib'),
('Зависимость - Single',2014,true,'VARIOUS_ARTISTS'),
('Helping Hands…Live & Acoustic At The Masonic',2019,NULL,'Metallica'),
('The Very Best of The Doors',2007,NULL,'The Doors'),
('Jubel - Single',2014,NULL,'Klingande'),
('Magical Mystery Tour',1967,NULL,'The Beatles'),
('Hybrid Theory',2000,NULL,'Linkin Park'),
('Number Ones',2007,NULL,'Stevie Wonder'),
('Dead Serious',1992,NULL,'Das EFX'),
('Psyence Fiction',1998,NULL,'UNKLE'),
('Guerillas in tha Mist',1992,NULL,'Da Lench Mob'),
('Jesus Piece',2012,NULL,'The Game'),
('Death Magnetic',2008,NULL,'Metallica'),
('My Dream',1997,NULL,'Yvette Michele'),
('Shine',2007,NULL,'Parov Stelar'),
('Innervisions',1973,NULL,'Stevie Wonder'),
('Power to the People and the Beats: Public Enemy''s Greatest Hits',2005,NULL,'Public Enemy'),
('Hidden Beach Recordings Presents: Unwrapped, Vol. 2',2002,true,'VARIOUS_ARTISTS'),
('Le Professionnel Soundtrack',1984,NULL,'Ennio Morricone'),
('The Brand New Heavies',1992,NULL,'The Brand New Heavies'),
('Song For You (Jacques Greene Remix) - Single',2019,NULL,'Rhye'),
('As I Am',2007,NULL,'Alicia Keys'),
('What the World is Coming To',1977,NULL,'Dexter Wansel'),
('Тает лёд - Single',2017,true,'VARIOUS_ARTISTS'),
('Into the Wind',2010,NULL,'Bei Bei & Shawn Lee'),
('Effet miroir',2018,NULL,'Zaz'),
('Seasoned Veteran',1996,NULL,'Richie Rich'),
('The Chronic',1992,NULL,'Dr. Dre'),
('Under My Skin',2004,NULL,'Avril Lavigne'),
('Fantastic',1983,NULL,'Wham!'),
('The Pianist Soundtrack',2002,true,'VARIOUS_ARTISTS'),
('100 Christmas Hits & Xmas Classics - The Greatest Holiday Songs Collection',2011,true,'VARIOUS_ARTISTS'),
('Follow Me Home',2011,NULL,'Jay Rock'),
('Camouflage',2017,NULL,'Lara Fabian'),
('Scream If You Wanna Go Faster',2001,NULL,'Geri Halliwell'),
('Death Unlimited',2004,NULL,'Norther'),
('Take Care',2011,true,'VARIOUS_ARTISTS'),
('Лети - Single',2018,true,'VARIOUS_ARTISTS'),
('Let it Be',1970,NULL,'The Beatles'),
('Shock Value',2007,NULL,'Timbaland'),
('Raise!',1981,NULL,'Earth, Wind & Fire'),
('How We Do',2003,NULL,'Das EFX'),
('Man vs. Machine',2002,NULL,'Xzibit'),
('Many Facez',1997,NULL,'Tracey Lee'),
('Я заболела тобой - Single',2018,NULL,'IOWA'),
('22 Jump Street Soundtrack',2014,true,'VARIOUS_ARTISTS'),
('Ready to Die',1994,NULL,'The Notorious B.I.G.'),
('The Miseducation of Lauryn Hill',1998,NULL,'Lauryn Hill'),
('The Godfather Soundtrack',1972,true,'VARIOUS_ARTISTS'),
('Mechanical Animals',1998,NULL,'Marilyn Manson'),
('Conspiracy Pt. I',2011,NULL,'Gesaffelstein'),
('The Bridge',2009,NULL,'Melanie Fiona'),
('Greatest Hits - Chapter One',2001,NULL,'Backstreet Boys'),
('Ennio Morricone Remixes, Vol. 2',2003,true,'VARIOUS_ARTISTS'),
('Ill Na Na',1996,NULL,'Foxy Brown'),
('H2LO',2017,NULL,'Loboda'),
('Make the Music 2000',1999,NULL,'Rahzel'),
('Waterfall (feat. P!nk & Sia) - Single',2017,NULL,'Stargate'),
('Regulate...G Funk Era',1994,NULL,'Warren G'),
('Triforce Tunes (4 level)',2020,true,'VARIOUS_ARTISTS'),
('The Untold Truth',1993,NULL,'Illegal'),
('Girls of Summer - Single',2002,true,'VARIOUS_ARTISTS'),
('The Boss',1979,NULL,'Diana Ross'),
('Bangin'' West Coast',2007,NULL,'Soopafly'),
('The Blue God',2008,NULL,'Martina Topley-Bird'),
('Soulful Strut',1996,NULL,'Grover Washington, Jr.'),
('Death Row Greatest Hits',1996,true,'VARIOUS_ARTISTS'),
('The 2nd Law',2012,NULL,'Muse'),
('Gap Band V: Jammin''',1983,NULL,'The Gap Band'),
('It''s Been a Long Time Coming',2000,NULL,'Mykill Miers'),
('Dial ''M'' for Monkey',2003,NULL,'Bonobo'),
('Secret Treaties',1974,NULL,'Blue Öyster Cult'),
('Tha Connect',2009,NULL,'Willy Northpole'),
('Travelling Without Moving',1996,NULL,'Jamiroquai'),
('Kaji Meiko no Hajiki Uta',1973,NULL,'Meiko Kaji'),
('The Best of Radiohead',2008,true,'VARIOUS_ARTISTS'),
('Signs of Life',2005,NULL,'Poets of the Fall'),
('Blow Up Your Video',1988,NULL,'AC/DC'),
('Honkin'' on Bobo',2004,NULL,'Aerosmith'),
('Попытка №5',2001,true,'VARIOUS_ARTISTS'),
('Days to Come',2006,true,'VARIOUS_ARTISTS'),
('Ayo',2017,NULL,'Ayo'),
('Bangir Bangir',2015,NULL,'Gulsen'),
('Lip Lock',2013,NULL,'Eve'),
('Blowback',2001,NULL,'Tricky'),
('Let Go',2002,NULL,'Avril Lavigne'),
('Get On Up Soundtrack',2014,NULL,'James Brown'),
('Flute Concertos',2008,NULL,'Johann Sebastian Bach'),
('The Symphonies',2003,NULL,'Ludwig van Beethoven'),
('Back to the Future Soundtrack',1985,true,'VARIOUS_ARTISTS'),
('Rubber Factory',2004,NULL,'The Black Keys'),
('Licensed to Ill',1986,NULL,'Beastie Boys'),
('I''m Still Here - Single',2018,NULL,'Sia'),
('What is Love?',2018,NULL,'Clean Bandit'),
('Then and Now',1988,NULL,'Grover Washington, Jr.'),
('Glasshouse',2017,NULL,'Jessie Ware'),
('Dangerous',1992,NULL,'Michael Jackson'),
('Never Too Much',1981,NULL,'Luther Vandross'),
('Believer',2017,NULL,'Imagine Dragons'),
('Copasetic & Cool',2002,NULL,'Hil St. Soul'),
('Soundtracks',2007,NULL,'DJ Deckstream'),
('Grand Collection, часть 3',2011,NULL,'Стас Михайлов'),
('Flesh Eating Disco Zombies versus The Bionic Hookers From Mars',1996,NULL,'London Funk Allstars'),
('Rockstar Mentality',2007,NULL,'Shop Boyz'),
('Nirvana',2002,true,'VARIOUS_ARTISTS'),
('LAX',2008,NULL,'The Game'),
('The North Borders',2013,NULL,'Bonobo'),
('Bacdafucup: Part II',2002,NULL,'Onyx'),
('Coffee Shop Selection',2015,NULL,'Gramatik'),
('Game Theory',2006,NULL,'The Roots'),
('To Be Loved: The Best of Papa Roach',2010,NULL,'Papa Roach'),
('Black Roses',1990,NULL,'Inner Circle'),
('Ray of Light',1998,NULL,'Madonna'),
('Как располагать к себе людей',2016,NULL,'Карнеги Дейл'),
('Бедные тоже смеются',2008,NULL,'Карандаш'),
('Вавилон - Single',2004,NULL,'Кипелов'),
('Moody Blue',1977,NULL,'Elvis Presley'),
('Business Never Personal',1992,NULL,'EPMD'),
('L.P.',1995,NULL,'The Rembrandts'),
('The Wonderful World of Christmas',1971,NULL,'Elvis Presley'),
('Dance to the Disco Sax of Monk Higgins',1974,NULL,'Monk Higgins'),
('Honor Amongst Thevz',1997,NULL,'40 Thevz'),
('Ridin'' Dirty',1996,NULL,'UGK'),
('Mr. Smith',1995,NULL,'LL Cool J'),
('Возня в грязи - Single',2018,NULL,'Ленинград'),
('Bottoms Up',2012,NULL,'Obie Trice'),
('Import',2016,NULL,'IOWA'),
('Femme Fatale',2007,NULL,'Wolf Myer Orchestra'),
('Compton',2015,NULL,'Dr. Dre'),
('Mint',2019,NULL,'Alice Merton'),
('Jade Bird',2019,NULL,'Jade Bird'),
('Ixnay on the Hombre',1997,NULL,'The Offspring'),
('Dogg Food',1995,NULL,'Tha Dogg Pound'),
('Affection',1989,NULL,'Lisa Stansfield'),
('Funkmaster Flex Presents 60 Minutes of Funk vol. 1',1995,true,'VARIOUS_ARTISTS'),
('Liebe ist für alle da',2009,NULL,'Rammstein'),
('When it Falls',2004,NULL,'Zero 7'),
('702',1999,NULL,'702'),
('King',2006,NULL,'T.I.'),
('Сестра Керри',2016,NULL,'Драйзер Теодор'),
('2Pacalypse Now',1991,NULL,'2Pac'),
('Zaz',2010,NULL,'Zaz'),
('Long Way Home',2016,NULL,'Låpsley'),
('Beatles for Sale',1964,NULL,'The Beatles'),
('Essential Speed Garage',1998,true,'VARIOUS_ARTISTS'),
('Back in ''72',1973,NULL,'Bob Seger'),
('2001',1999,NULL,'Dr. Dre'),
('Глаза цвета неба',2001,NULL,'Валерия'),
('Unholy Terror',2001,NULL,'W.A.S.P.'),
('Bad as I Wanna B',1996,NULL,'MC Lyte'),
('Milestones',1958,NULL,'Miles Davis'),
('This is Gizelle Smith & The Mighty Mocambos',2010,NULL,'Gizelle Smith & The Mighty Mocambos'),
('Girl on Fire',2012,NULL,'Alicia Keys'),
('Дерзкая (feat. Тимати) - Single',2015,true,'VARIOUS_ARTISTS'),
('Magic Potion',2006,NULL,'The Black Keys'),
('Reality Show',2015,NULL,'Jazmine Sullivan'),
('Kill Bill Vol.2 Soundtrack',2004,true,'VARIOUS_ARTISTS'),
('Respect M.E.',2006,true,'VARIOUS_ARTISTS'),
('Roxbury 02119',1994,NULL,'Ed O.G. & Da Bulldogs'),
('''lectric Lady',1976,NULL,'Carol Williams'),
('A Rush of Blood to the Head',2002,NULL,'Coldplay'),
('Walk This Way (VLS)',1986,NULL,'Run-D.M.C.'),
('Electra Heart',2012,NULL,'Marina & The Diamonds'),
('Quik is the Name',1991,NULL,'DJ Quik'),
('Gold: Greatest Hits',2003,NULL,'Gheorghe Zamfir'),
('Start Something',2004,NULL,'Lostprophets'),
('Places and Spaces',1975,NULL,'Donald Byrd'),
('Classic',2010,NULL,'Rah Digga'),
('Christina Aguilera',1999,NULL,'Christina Aguilera'),
('Pumped Up - Single',2017,NULL,'Klingande'),
('Трилогия желания',2015,NULL,'Драйзер Теодор'),
('Abendglocken - Die Schonsten Russland-Melodien',1988,NULL,'James Last'),
('Greatest Hits',1981,NULL,'Queen'),
('Blossom',2006,true,'VARIOUS_ARTISTS'),
('Isaac Delusion',2014,NULL,'Isaac Delusion'),
('Forever for Now',2014,NULL,'LP'),
('Архипелаг ГУЛАГ',2012,NULL,'Солженицын Александр'),
('A Hard Day''s Night',1964,NULL,'The Beatles'),
('Uncut Dope: Geto Boys'' Best',1992,NULL,'Geto Boys'),
('LSD',2019,NULL,'LSD'),
('The Best',2014,NULL,'Мумий Тролль'),
('Something to Tell You',2017,NULL,'HAIM'),
('Winners',1980,NULL,'Kleeer'),
('The Best Of The Gap Band',1994,NULL,'The Gap Band'),
('Piano Concertos',2001,NULL,'Felix Mendelssohn'),
('Le Best Of',2004,NULL,'Hélène Ségara'),
('Yes ''N'' Deed (The E.P.)',1994,NULL,'Society'),
('Operation Stackola',1995,NULL,'Luniz'),
('Hi-Fi Serious',2002,NULL,'A'),
('Still ',1981,NULL,'Joy Division'),
('Tougher Than Leather',1988,NULL,'Run-D.M.C.'),
('Attack & Release',2008,NULL,'The Black Keys'),
('A Date with The Everly Brothers',1960,NULL,'The Everly Brothers'),
('Release Therapy',2006,NULL,'Ludacris'),
('CAN''T STOP THE FEELING! (Original Song From DreamWorks Animation''s "Trolls") - Single',2016,true,'VARIOUS_ARTISTS'),
('Lovers Rock',2000,NULL,'Sade'),
('Once Upon a Time in the West Expanded Soundtrack',1968,NULL,'Ennio Morricone'),
('Fallen',2003,NULL,'Evanescence'),
('Ticket to the World',2013,NULL,'Ayo'),
('Seven & Seven',1998,NULL,'MC Lyte'),
('Adrian Thaws',2014,NULL,'Tricky'),
('Love for the Streets',2002,NULL,'Caesars Palace'),
('Idlewild',2006,NULL,'Outkast'),
('Парень - Single',2018,true,'VARIOUS_ARTISTS'),
('good kid, m.A.A.d city',2012,true,'VARIOUS_ARTISTS'),
('Taki Taki (feat. Selena Gomez, Ozuna & Cardi B) - Single',2018,NULL,'DJ Snake'),
('Bootlegs & B-Sides',1994,NULL,'Ice Cube'),
('Days Go By CDS',2002,NULL,'Dirty Vegas'),
('Ensiferum',2001,NULL,'Ensiferum'),
('Bizarre Ride II The Pharcyde',1992,NULL,'The Pharcyde'),
('Got to Be Real: The Best of Cheryl Lynn',1996,NULL,'Cheryl Lynn'),
('Down to Earth',1990,NULL,'Monie Love'),
('Chemically Imbalanced',2006,NULL,'Ying Yang Twins'),
('Get Down Saturday Night',1990,NULL,'Oliver Cheatham'),
('Красное Белое (Single)',2018,NULL,'#2Маши'),
('Grease Soundtrack',1978,true,'VARIOUS_ARTISTS'),
('Freeek! CDS',2002,NULL,'George Michael'),
('Doggumentary',2011,NULL,'Snoop Dogg'),
('Prime Cuts',1999,NULL,'Grover Washington, Jr.'),
('Революция - Single',2013,true,'VARIOUS_ARTISTS'),
('Same as it Never Was',2008,NULL,'The Herbaliser'),
('Сколько Взорвется Бомб? (EP)',2012,NULL,'Порнофильмы'),
('Strength & Loyalty',2007,NULL,'Bone Thugs-N-Harmony'),
('Man About Town',2016,NULL,'Mayer Hawthorne'),
('It''s Your World',1976,NULL,'Gil Scott-Heron & Brian Jackson'),
('The Big Picture',2000,NULL,'Big L'),
('Am I Wrong EP',2000,NULL,'Étienne de Crécy'),
('Meloman',2007,NULL,'Krec'),
('11 Short Stories of Pain & Glory',2017,NULL,'Dropkick Murphys'),
('No Time for Dreaming',2011,NULL,'Charles Bradley'),
('Relatos Salvajes Soundtrack',2014,true,'VARIOUS_ARTISTS'),
('American Gangster Soundtrack',2007,true,'VARIOUS_ARTISTS'),
('Smooth Talk',1977,NULL,'Evelyn "Champagne" King'),
('Nouvelle Vague',2004,NULL,'Nouvelle Vague'),
('Piano Sonatas No. 8, 14, 17, 23',2003,NULL,'Ludwig van Beethoven'),
('I Love to Dance',1979,NULL,'Kleeer'),
('Spirit',2019,NULL,'Rhye'),
('Historian',2018,NULL,'Lucy Dacus'),
('Hustlin'' - Single',2006,NULL,'Rick Ross'),
('The Dutchess',2006,NULL,'Fergie'),
('Ear to the Street',1993,NULL,'The Conscious Daughters'),
('Born 2 Rap',2019,NULL,'The Game'),
('In or Out - Single',2017,NULL,'Elina Born'),
('Untrue',2007,NULL,'Burial'),
('Auf Wiedersehn',1974,NULL,'Demis Roussos'),
('Chuck',2004,true,'VARIOUS_ARTISTS'),
('Up Close and Personal',2001,NULL,'Angie Martinez'),
('On a Mission',2011,NULL,'Katy B'),
('The Definitive Singles Collection 1984-2004',2004,NULL,'a-ha'),
('Dance, Dance, Dance: The Best of Chic',1991,NULL,'Chic'),
('The Mirror Conspiracy',2000,NULL,'Thievery Corporation'),
('The Best That I Could Do 1978-1988',1997,NULL,'John Mellencamp'),
('Station Identification',1995,NULL,'Channel Live'),
('Down with the King',1993,NULL,'Run-D.M.C.'),
('The God Box',2017,NULL,'David Banner'),
('The Best of Cold Chillin''',1996,NULL,'Biz Markie'),
('Oral Fixation, Vol. 2',2006,NULL,'Shakira'),
('Closer (feat. Halsey) - Single',2016,true,'VARIOUS_ARTISTS'),
('Легенды русского рока: Кино',2015,true,'VARIOUS_ARTISTS'),
('Listen',2014,NULL,'David Guetta'),
('Black Holes and Revelations',2006,NULL,'Muse'),
('Sareyo Sareyo Kanashimi no Shirabe',1974,NULL,'Meiko Kaji'),
('Time Out of Mind',1989,NULL,'Grover Washington, Jr.'),
('Hangover (feat. Snoop Dogg) - Single',2014,true,'VARIOUS_ARTISTS'),
('JHUD',2014,NULL,'Jennifer Hudson'),
('Ludaversal',2015,true,'VARIOUS_ARTISTS'),
('Избранное 3',2002,NULL,'Сектор Газа'),
('Breaking Bad Soundtrack',2010,true,'VARIOUS_ARTISTS'),
('The Complete Motown Singles Vol. 3: 1963',2005,true,'VARIOUS_ARTISTS'),
('Избранное',1996,NULL,'Сектор Газа'),
('Little Hero Going To the Bar',2012,NULL,'8-Bitchin’tendo'),
('RAMMSTEIN',2019,NULL,'Rammstein'),
('All Visible Objects',2020,NULL,'Moby'),
('Greatest Hits: Souvenir Edition',2013,true,'VARIOUS_ARTISTS'),
('Blowout Comb',1994,NULL,'Digable Planets'),
('Sadnecessary',2013,NULL,'Milky Chance'),
('Lost on You (Deluxe Edition)',2017,NULL,'LP'),
('To Pimp a Butterfly',2015,true,'VARIOUS_ARTISTS'),
('Greatest Hits - Chapter One',2012,NULL,'Kelly Clarkson'),
('Turn Blue',2014,NULL,'The Black Keys'),
('БезИМЯнный',2004,NULL,'Карандаш'),
('Say Yes Evolved',2016,NULL,'Iyeoka'),
('X&Y',2005,NULL,'Coldplay'),
('Arrival',1976,NULL,'ABBA'),
('A Strange Arrangement',2009,NULL,'Mayer Hawthorne'),
('Iron',2004,NULL,'Ensiferum'),
('Revival',2017,true,'VARIOUS_ARTISTS'),
('For a Few Dollars More Expanded Soundtrack',1965,NULL,'Ennio Morricone'),
('Woman',2016,true,'VARIOUS_ARTISTS'),
('I''m Serious',2001,NULL,'T.I.'),
('Warning',2000,NULL,'Green Day'),
('DAMN.',2017,true,'VARIOUS_ARTISTS'),
('Human',2017,NULL,'Rag''n''Bone Man'),
('The Massacre',2005,NULL,'50 Cent'),
('The Ride',2017,NULL,'Nelly Furtado'),
('Water for Your Soul',2015,NULL,'Joss Stone'),
('Let There Be Rock',1977,NULL,'AC/DC'),
('Mister Magic',1975,NULL,'Grover Washington, Jr.'),
('Hidden Beach Recordings Presents: Unwrapped, Vol. 4',2005,NULL,'Hidden Beach Recordings'),
('The Woman in Me',1995,NULL,'Shania Twain'),
('Feels So Good',1975,NULL,'Grover Washington, Jr.'),
('Blunted on Reality',1994,NULL,'Fugees'),
('Distant Relatives',2010,NULL,'Nas & Damian Marley'),
('Don''t Wake the Riot',2016,NULL,'Black Pistol Fire'),
('Розовое вино (feat. Feduk) - Single',2017,NULL,'Элджей'),
('To Da Beat Ch''all',1996,NULL,'MC Breed'),
('Tuxedo Remixes',2015,NULL,'Tuxedo'),
('A One of a Kind Love Affair (The Anthology)',1991,NULL,'The Spinners'),
('Live at the Bijou',1977,NULL,'Grover Washington, Jr.'),
('Get Ready',1982,NULL,'Kleeer'),
('Business Casual',2010,NULL,'Chromeo'),
('Dvořák. Serenades, Op. 22 & 44',1981,NULL,'Antonín Dvořák'),
('In Utero',1993,NULL,'Nirvana'),
('The Godfather II Soundtrack',1974,true,'VARIOUS_ARTISTS'),
('Nostalgia for 8-Bit',2017,true,'VARIOUS_ARTISTS'),
('Lift Your Spirit',2013,true,'VARIOUS_ARTISTS'),
('You Could Have It So Much Better',2005,NULL,'Franz Ferdinand'),
('The Fragile',1999,NULL,'Nine Inch Nails'),
('Prawns',1995,NULL,'Big Cheese All Stars'),
('Shut Your Mouth (Single)',2001,NULL,'Pain'),
('Омлет',2009,NULL,'Ленин'),
('Teenage Dream',2010,NULL,'Katy Perry'),
('Safe Trip Home',2008,NULL,'Dido'),
('Blood',2018,NULL,'Rhye'),
('Unwrapped Vol. 5.0: The Collipark Cafe Sessions',2008,NULL,'Hidden Beach Recordings'),
('Mind Body & Soul',2004,NULL,'Joss Stone'),
('Quixotic',2003,NULL,'Martina Topley-Bird'),
('Peace is the Mission (Extended)',2015,NULL,'Major Lazer'),
('Голод',2003,NULL,'Звери'),
('BUSH',2015,true,'VARIOUS_ARTISTS'),
('Hot Shot',2000,NULL,'Shaggy'),
('Charango',2002,NULL,'Morcheeba'),
('I Am the West',2010,NULL,'Ice Cube'),
('Nue',2001,NULL,'Lara Fabian'),
('For the Love of You',1997,NULL,'Candy Dulfer'),
('Sound of a Woman',2014,true,'VARIOUS_ARTISTS'),
('Best of Chris Isaak',2006,NULL,'Chris Isaak'),
('Цвет настроения синий - Single',2018,NULL,'Филипп Киркоров'),
('Car Wheels on a Gravel Road',1998,NULL,'Lucinda Williams'),
('Soldier of Love',2010,NULL,'Sade'),
('The Warrior''s Code',2005,NULL,'Dropkick Murphys'),
('The New Breed',1993,NULL,'MC Breed'),
('The Marshall Mathers LP',2000,NULL,'Eminem'),
('Promise',1985,NULL,'Sade'),
('Adam''s Case Files',2008,NULL,'88-Keys'),
('Мутные времена',2009,NULL,'Jahmal TGK'),
('Call on Me EP',2004,true,'VARIOUS_ARTISTS'),
('Gamers',1996,NULL,'The Conscious Daughters'),
('The Stranger',1977,NULL,'Billy Joel'),
('Return to Childhood',2014,NULL,'8-Bitchin’tendo'),
('Here',2016,NULL,'Alicia Keys'),
('Everything is Great',1979,NULL,'Inner Circle'),
('Би-2',2000,true,'VARIOUS_ARTISTS'),
('Genie (feat. Mayer Hawthorne) - EP',2017,NULL,'Busy P'),
('The Jam EP',1997,NULL,'A Tribe Called Quest'),
('This Is How We Do It',1995,NULL,'Montell Jordan'),
('How High Soundtrack',2001,true,'VARIOUS_ARTISTS'),
('Exciter',2001,NULL,'Depeche Mode'),
('The Voyager',2014,NULL,'Jenny Lewis'),
('No One Can Do it Better',1989,NULL,'The D.O.C.'),
('Savior - Single',2018,NULL,'Iggy Azalea'),
('The Album',1977,NULL,'ABBA'),
('Fire Dance with Me',2014,NULL,'Charlotte Qvale'),
('The Matrix Reloaded: The Album',2003,true,'VARIOUS_ARTISTS'),
('Медуза - Single',2018,NULL,'MATRANG'),
('Hip Hop is Dead',2006,NULL,'Nas'),
('Triforce Tunes',2012,true,'VARIOUS_ARTISTS'),
('Impressions - The Covers EP',2011,NULL,'Mayer Hawthorne'),
('Tuxedo',2015,NULL,'Tuxedo'),
('Edvard Grieg - Peer Gynt Suite, Jean Sibelius - Valse Triste (1982-1984)',1984,true,'VARIOUS_ARTISTS'),
('Mardi Gras',1972,NULL,'Creedence Clearwater Revival'),
('Burial',2006,NULL,'Burial'),
('Ride the Lightning',1984,NULL,'Metallica'),
('Дай Мне Слово - Single',2013,true,'VARIOUS_ARTISTS'),
('The 18th Letter',1997,NULL,'Rakim'),
('Morning Birds',1996,NULL,'David Sun'),
('War & Peace Vol. 2 (The Peace Disc)',2000,NULL,'Ice Cube'),
('Golden Age Against The Machine',2014,NULL,'Shawn Lee'),
('Лучшие песни. Часть I',2008,NULL,'Михаил Шуфутинский'),
('The Sign',1993,NULL,'Ace of Base'),
('Dummy',1994,NULL,'Portishead'),
('The Main Ingredient',1994,NULL,'Pete Rock & C.L. Smooth'),
('Funk Wav Bounces Vol. 1',2017,NULL,'Calvin Harris'),
('Fragments of Freedom',2000,NULL,'Morcheeba'),
('Между нами любовь - Single',2018,NULL,'SEREBRO'),
('The Ultimate Collection 1968-2003',2003,NULL,'Joe Cocker'),
('Prophets of Rage',2017,NULL,'Prophets of Rage'),
('BETSY',2017,NULL,'Betsy'),
('Kings of Crunk',2004,NULL,'Lil Jon & The East Side Boyz'),
('Do You Wanna Ride?',1995,NULL,'Adina Howard'),
('Greatest Hits',2008,NULL,'Creedence Clearwater Revival'),
('Judgment Night Soundtrack',1993,true,'VARIOUS_ARTISTS'),
('Love Death Immortality',2014,true,'VARIOUS_ARTISTS'),
('Westworld Season 3 Soundtrack',2020,NULL,'Ramin Djawadi'),
('California EP',2018,true,'VARIOUS_ARTISTS'),
('Grace Potter & The Nocturnals',2010,NULL,'Grace Potter & The Nocturnals'),
('Anti',2016,NULL,'Rihanna'),
('Nevermind',1991,NULL,'Nirvana'),
('Born to Be Wild',1992,NULL,'Steppenwolf'),
('Fly on the Wall',1985,NULL,'AC/DC'),
('Me Against the World',1995,NULL,'2Pac'),
('Mükemmel',2014,NULL,'Hande Yener'),
('Man of the Woods',2018,true,'VARIOUS_ARTISTS'),
('The Best of MC Breed',1995,true,'VARIOUS_ARTISTS'),
('KRS ONE',1995,NULL,'KRS-One'),
('В круге первом',2015,NULL,'Солженицын Александр'),
('Read My Lips',2002,NULL,'Sophie Ellis-Bextor'),
('Permanent Vacation',1987,NULL,'Aerosmith'),
('Back From Hell',1990,NULL,'Run-D.M.C.'),
('Nuovo Cinema Paradiso Soundtrack',1988,NULL,'Ennio Morricone'),
('The Greatest (feat. Kendrick Lamar) - Single',2016,NULL,'Sia'),
('This is Acting',2016,NULL,'Sia'),
('Creedence Clearwater Revival',1968,NULL,'Creedence Clearwater Revival'),
('Toni Braxton',1993,NULL,'Toni Braxton'),
('Buhloone Mind State',1993,NULL,'De La Soul'),
('Gangsta Party',2007,NULL,'Daz Dillinger'),
('Very Mercenary',1999,NULL,'The Herbaliser'),
('Just Push Play',2001,NULL,'Aerosmith'),
('Kill ''Em All',1983,NULL,'Metallica'),
('Молчишь на меня - Single',2018,NULL,'IOWA'),
('Good Days',2020,NULL,'Broken Back'),
('So Sad So Sexy',2018,NULL,'Lykke Li'),
('All Killer No Filler',2001,true,'VARIOUS_ARTISTS'),
('Золотая коллекция',2006,NULL,'Михаил Круг'),
('Карма Рабочих',2013,NULL,'Порнофильмы'),
('It''s Dark and Hell is Hot',1998,NULL,'DMX'),
('The Best of Seryoga',2008,NULL,'Серёга'),
('Until the End of Time',2001,NULL,'2Pac'),
('Dr. Lecter',2011,NULL,'Action Bronson'),
('Ray Soundtrack',2004,NULL,'Ray Charles'),
('Monumental',2018,NULL,'Kadebostany'),
('Dirty Deeds Done Dirt Cheap',1976,NULL,'AC/DC'),
('Lara Fabian',2000,NULL,'Lara Fabian'),
('Knowle West Boy',2008,NULL,'Tricky'),
('Saxuality',1990,NULL,'Candy Dulfer'),
('Flute-In',1971,NULL,'Bobbi Humphrey'),
('Interstellar',2008,true,'VARIOUS_ARTISTS'),
('To the 5 Boroughs',2004,NULL,'Beastie Boys'),
('Never Coming Out EP',1994,NULL,'Pete Rock & C.L. Smooth'),
('Chocolate Starfish and the Hot Dog Flavored Water',2000,NULL,'Limp Bizkit'),
('Secrets',1978,NULL,'Gil Scott-Heron & Brian Jackson'),
('Chulahoma EP',2006,NULL,'The Black Keys'),
('A Girl Like Me',2001,NULL,'Emma Bunton'),
('Celebrate Me Home',1977,NULL,'Kenny Loggins'),
('The Gathering',1999,NULL,'Infected Mushroom'),
('You Will Never Know EP',2013,NULL,'Imany'),
('Anuthatantrum',1996,NULL,'Da Brat'),
('Platinum Hits',2016,NULL,'Jason Derulo'),
('That''s Them....',1997,NULL,'Artifacts'),
('Take My Time',2013,NULL,'Highway Superstar'),
('Motor Sport - Single',2017,NULL,'Migos, Nicki Minaj & Cardi B'),
('My Own Worst Enemy',2004,NULL,'Edo.G'),
('t.A.T.u. The Best',2006,NULL,'t.A.T.u.'),
('Pure',1996,NULL,'Lara Fabian'),
('Grand Collection',2008,NULL,'Ляпис Трубецкой'),
('Verão',2007,NULL,'Sabrepulse'),
('The Shining',2006,NULL,'J Dilla'),
('A Thousand Suns',2010,true,'VARIOUS_ARTISTS'),
('Stillmatic',2001,NULL,'Nas'),
('Atari-Ska L''Attack',2007,NULL,'Dubmood'),
('Jazz Hop Soul',1994,NULL,'Clever Jeff'),
('Vagina Diner',1993,NULL,'Akinyele'),
('Dive',2011,NULL,'Tycho'),
('Bad',1987,NULL,'Michael Jackson'),
('The Very Best of Deep Purple',2000,NULL,'Deep Purple'),
('Fever',2001,NULL,'Kylie Minogue'),
('Heard it in a Past Life',2019,NULL,'Maggie Rogers'),
('x',2014,NULL,'Ed Sheeran'),
('Episodes of a Hustla',1996,NULL,'Big Noyd'),
('Put it in Your Mouth EP',1996,NULL,'Akinyele'),
('Hardwired…To Self-Destruct',2016,NULL,'Metallica'),
('Garage Inc.',1998,NULL,'Metallica'),
('Voyage',1978,NULL,'Brian Bennett'),
('Open Our Eyes',1974,NULL,'Earth, Wind & Fire'),
('The Big Come Up',2002,NULL,'The Black Keys'),
('Live Through This',1994,NULL,'Hole'),
('Doll Domination',2008,NULL,'The Pussycat Dolls'),
('Northern Sulphuric Soul',1998,NULL,'Rae & Christian'),
('Soon it Will Be Cold Enough',2006,NULL,'Emancipator'),
('Bring Out the Sound',2018,NULL,'The Herbaliser'),
('The Declaration',2008,NULL,'Ashanti'),
('Pulp Fiction Soundtrack',1994,true,'VARIOUS_ARTISTS'),
('Make a Scene',2011,NULL,'Sophie Ellis-Bextor'),
('Team - Single',2016,NULL,'Iggy Azalea'),
('Ego Trippin''',2008,NULL,'Snoop Dogg'),
('The Very Best of TLC',2007,true,'VARIOUS_ARTISTS'),
('Live Bullet',1976,NULL,'Bob Seger & The Silver Bullet Band'),
('Funky Divas',1992,NULL,'En Vogue'),
('The Good, The Bad & The Crazy (Remixes)',2015,NULL,'Imany'),
('Swop',2008,NULL,'Club des Belugas'),
('Best of the Rasmus 2001-2009',2009,true,'VARIOUS_ARTISTS'),
('Summer Days (Roosevelt Remix) - Single',2019,NULL,'Rhye'),
('Toss it Up (CDM)',1996,NULL,'Makaveli'),
('Renegades',2000,NULL,'Rage Against The Machine'),
('TIM',2019,NULL,'Avicii'),
('Flesh Tone',2010,NULL,'Kelis'),
('So Natural',1993,NULL,'Lisa Stansfield'),
('White Women',2014,true,'VARIOUS_ARTISTS'),
('Britney',2001,NULL,'Britney Spears'),
('Jazzmatazz Volume 1',1993,NULL,'Guru'),
('Party and Bullshit (Promo VLS)',1993,NULL,'The Notorious B.I.G.'),
('Trap Muzik',2003,NULL,'T.I.'),
('Reality',1998,NULL,'Smooth'),
('Тяжеловес',2013,true,'VARIOUS_ARTISTS'),
('Paradise Island',1999,NULL,'David Sun'),
('Halfway Between the Gutter and the Stars',2000,NULL,'Fatboy Slim'),
('Baccara',1977,NULL,'Baccara'),
('Hazardous',2009,NULL,'Vanessa Amorosi'),
('Generation EFX',1998,NULL,'Das EFX'),
('Breaking Atoms',1991,NULL,'Main Source'),
('Crystal Castles',2008,NULL,'Crystal Castles'),
('The Mix-Up',2007,NULL,'Beastie Boys'),
('Highest Hopes: The Best of Nightwish',2005,true,'VARIOUS_ARTISTS'),
('You da Baddest (feat. Nicki Minaj) - Single',2017,true,'VARIOUS_ARTISTS'),
('Get a Grip',1993,NULL,'Aerosmith'),
('Misophonia',2018,NULL,'Chris Joss'),
('Кирпичи тяжелы',1996,NULL,'Кирпичи'),
('Everything is 4',2015,true,'VARIOUS_ARTISTS'),
('30',2015,true,'VARIOUS_ARTISTS'),
('When I Was Young EP',2017,NULL,'MØ'),
('Black Rose',2008,NULL,'Hil St. Soul'),
('The Master',1999,NULL,'Rakim'),
('Государь',2012,NULL,'Макиавелли Никколо'),
('Mary Jane Girls',1983,NULL,'Mary Jane Girls'),
('Crunk Rock',2010,NULL,'Lil Jon'),
('From Elvis In Memphis',1969,NULL,'Elvis Presley'),
('Paper Trail',2008,NULL,'T.I.'),
('Winter In America',1974,NULL,'Gil Scott-Heron & Brian Jackson'),
('Willy and the Poorboys',1969,NULL,'Creedence Clearwater Revival'),
('The Best of Cold Chillin''',1994,NULL,'Biz Markie'),
('After the Disco',2014,NULL,'Broken Bells'),
('Organ Symphony etc',2007,NULL,'Camille Saint-Saëns'),
('Blossom',2017,NULL,'Milky Chance'),
('Labcabincalifornia',1995,NULL,'The Pharcyde'),
('Rise Up - Single',2016,true,'VARIOUS_ARTISTS'),
('Death Rides a Horse Soundtrack',1968,NULL,'Ennio Morricone'),
('Diana',1980,NULL,'Diana Ross'),
('Late Registration',2005,NULL,'Kanye West'),
('Ritual of Battle',2007,NULL,'Army of the Pharaohs'),
('Liquid Swords',1995,NULL,'GZA'),
('Туманы',2016,NULL,'Макс Барских'),
('Greatest Hitz',2005,NULL,'Limp Bizkit'),
('LOVE 3X Remixes EP',2015,true,'VARIOUS_ARTISTS'),
('I Want It All',1999,NULL,'Warren G'),
('Play',1999,NULL,'Moby'),
('UGK 4 LIFE',2009,NULL,'UGK'),
('Избранное',1995,NULL,'Владимир Высоцкий'),
('Розыгрыш OST',2009,NULL,'Noize MC'),
('Justified',2002,NULL,'Justin Timberlake'),
('Da Undaground Heat vol. 1',2003,NULL,'MC Lyte'),
('The Diary of Alicia Keys',2003,NULL,'Alicia Keys'),
('Vivid',1988,NULL,'Living Colour'),
('You Make it Feel Like Christmas',2017,NULL,'Gwen Stefani'),
('Stranger In Town',1978,NULL,'Bob Seger & The Silver Bullet Band'),
('Get Rich or Die Tryin'' Soundtrack',2005,true,'VARIOUS_ARTISTS'),
('The First Album',1984,NULL,'Run-D.M.C.'),
('The Matrix Soundtrack',1999,true,'VARIOUS_ARTISTS'),
('By Triagrutrika, Pt. 1',2018,NULL,'Триагрутрика'),
('Mountain Stream',1999,NULL,'David Sun'),
('The Queen is Dead',1986,NULL,'The Smiths'),
('Kill Bill Vol.1 Soundtrack',2003,true,'VARIOUS_ARTISTS'),
('ESQ. The Revelation',2014,NULL,'Tracey Lee'),
('Despacito (feat. Daddy Yankee) - Single',2017,NULL,'Luis Fonsi'),
('Once Upon a Time in the West Soundtrack',1968,NULL,'Ennio Morricone'),
('Long Way Back',2003,NULL,'T-Love'),
('All I Need',2016,NULL,'Foxes'),
('(What''s the Story) Morning Glory?',1995,NULL,'Oasis'),
('Sports',1983,NULL,'Huey Lewis & The News'),
('Alright, Still',2006,NULL,'Lily Allen'),
('Nasir',2018,NULL,'Nas'),
('The Best of Cold Chillin''',1993,NULL,'Biz Markie'),
('How Great Thou Art',1966,NULL,'Elvis Presley'),
('Doctor''s Advocate',2006,NULL,'The Game'),
('Master of Puppets',1986,NULL,'Metallica'),
('Gravity at Last',2008,NULL,'Ayo'),
('Fijación Oral, Vol. 1',2005,NULL,'Shakira'),
('Californication',1999,NULL,'Red Hot Chili Peppers'),
('The Demon Diaries',2015,NULL,'Parov Stelar'),
('Swingers in Paradise',2004,NULL,'Hi-Fi Companions'),
('Knoc''s Ville',2002,true,'VARIOUS_ARTISTS'),
('Gasoline',2005,NULL,'Theory of a Deadman'),
('Revolution Radio',2016,NULL,'Green Day'),
('Mama''s Gun',2000,NULL,'Erykah Badu'),
('So Dark the Con of Man',2007,NULL,'Madcon'),
('No Doubt',1996,NULL,'702'),
('Вояж - Single',2017,NULL,'Ленинград'),
('Froot',2015,NULL,'Marina & The Diamonds'),
('100th Window',2003,NULL,'Massive Attack'),
('Грустный дэнс (feat. Артем Качер) - Single',2019,NULL,'Artik & Asti'),
('L.A. Divine',2017,NULL,'Cold War Kids'),
('Районы-кварталы',2004,NULL,'Звери'),
('I Want You',1976,NULL,'Marvin Gaye'),
('Reed Seed',1978,NULL,'Grover Washington, Jr.'),
('Night Walks',2010,NULL,'Hidden Orchestra'),
('Don''t Do It',1990,NULL,'Richie Rich'),
('Vanglorious Law',1990,NULL,'Queen Mother Rage'),
('Devotion',2012,NULL,'Jessie Ware'),
('Portishead',1997,NULL,'Portishead'),
('Lethal Injection',1993,NULL,'Ice Cube'),
('Greatest Hits',1975,NULL,'Leonard Cohen'),
('Love Deluxe',1992,NULL,'Sade'),
('Nate Dogg',2003,NULL,'Nate Dogg'),
('The Spotify Sessions EP',2017,NULL,'Sia'),
('The Best of Cold Chillin''',1991,NULL,'Biz Markie'),
('Into the Wild Soundtrack',2007,NULL,'Eddie Vedder'),
('The Hateful Eight Soundtrack',2015,true,'VARIOUS_ARTISTS'),
('Kush (feat. Snoop Dogg & Akon) - Single',2010,true,'VARIOUS_ARTISTS'),
('Forever My Lady',1991,NULL,'Jodeci'),
('Wanderland',2001,NULL,'Kelis'),
('Баклажан (feat. Рекорд Оркестр) - Single',2015,true,'VARIOUS_ARTISTS'),
('Automaton',2017,NULL,'Jamiroquai'),
('Lust for Life',2017,true,'VARIOUS_ARTISTS'),
('The Documentary 2',2015,NULL,'The Game'),
('Loyal to the Game',2004,NULL,'2Pac'),
('Second Round''s on Me',2006,NULL,'Obie Trice'),
('Get Rich or Die Tryin''',2003,NULL,'50 Cent'),
('The Complete Motown Singles, Vol. 4: 1964',2006,true,'VARIOUS_ARTISTS'),
('Stripped',2002,NULL,'Christina Aguilera'),
('Bunkka',2002,true,'VARIOUS_ARTISTS'),
('Str8 Off Tha Streetz Of Muthaphukkin Compton',1995,NULL,'Eazy-E'),
('Town Bidness, vol. 1',2010,NULL,'Richie Rich'),
('Famicom Connection',2005,NULL,'Sabrepulse'),
('Гуляй, мужик!',1992,true,'VARIOUS_ARTISTS'),
('Hello Nasty',1998,NULL,'Beastie Boys'),
('Gorillaz',2001,NULL,'Gorillaz'),
('The Best of Cold Chillin''',1988,NULL,'Biz Markie'),
('Turn This Mutha Out',1977,NULL,'Idris Muhammad'),
('Lo-Fi World',2012,NULL,'8-Bitchin’tendo'),
('Shy Guy CDS',1995,NULL,'Diana King'),
('Some Old Bullshit',1994,NULL,'Beastie Boys'),
('Chopin 200 ! - the Anniversary Collection',2010,true,'VARIOUS_ARTISTS'),
('Алсу',1999,NULL,'Алсу'),
('Ennio Morricone Remixes, Vol. 1',2003,true,'VARIOUS_ARTISTS'),
('Random Access Memories',2013,NULL,'Daft Punk'),
('Elvis'' Christmas Album',1957,NULL,'Elvis Presley'),
('The Battle of Los Angeles',1999,NULL,'Rage Against The Machine'),
('Dah Shinin''',1995,NULL,'Smif-N-Wessun'),
('Conspiracy Pt. II',2011,NULL,'Gesaffelstein'),
('Detours',2008,NULL,'Sheryl Crow'),
('Uptown Special',2015,NULL,'Mark Ronson'),
('The Best of Cold Chillin''',1989,NULL,'Biz Markie'),
('Return of the Mac',2007,NULL,'Prodigy of Mobb Deep'),
('It''s Not Me, It''s You',2009,NULL,'Lily Allen'),
('LOVE + FEAR',2019,true,'VARIOUS_ARTISTS'),
('The Age of the Understatement',2008,NULL,'The Last Shadow Puppets'),
('This is Dedicated to You (feat. Latoya WIlliams) - Single',2011,NULL,'Warren G'),
('В Питере - пить - Single',2016,true,'VARIOUS_ARTISTS'),
('Boom Boom - Single',2020,NULL,'LOBODA & PHARAOH'),
('Help!',1965,NULL,'The Beatles'),
('The Devil Made Me Remix',2004,NULL,'Paris'),
('Crazy in Love - Fifty Shades of Grey Version - Single',2014,NULL,'Sofia Karlberg'),
('The Torture Papers',2006,NULL,'Army of the Pharaohs'),
('Yellow Submarine',1969,NULL,'The Beatles'),
('Room Service',2001,NULL,'Roxette'),
('Don''t Be So Shy (Remixes)',2015,NULL,'Imany'),
('Fed Case',2017,NULL,'Richie Rich'),
('Hotel',2005,NULL,'Moby'),
('Кара-тэ',2005,NULL,'Смоки Мо'),
('Humanz',2017,true,'VARIOUS_ARTISTS'),
('Inner City Blues',1971,NULL,'Grover Washington, Jr.'),
('Recto Verso',2013,true,'VARIOUS_ARTISTS'),
('Taste the Music',1982,NULL,'Kleeer'),
('Survive the Summer - EP',2018,NULL,'Iggy Azalea'),
('I Want You - Single',2020,NULL,'MARUV & Boosin'),
('All the Time - Single',2019,NULL,'Zara Larsson'),
('Meteora',2003,NULL,'Linkin Park'),
('Heart To Mouth',2018,NULL,'LP'),
('Mutter',2001,NULL,'Rammstein'),
('Пирушка с привидениями и другие рассказы',2016,NULL,'Джером Клапка Джером'),
('Encore',2004,NULL,'Eminem'),
('Кара-тэ',2004,NULL,'Смоки Мо'),
('Post Traumatic',2018,NULL,'Mike Shinoda'),
('Going Out in Style',2011,NULL,'Dropkick Murphys'),
('Voyager',1978,NULL,'Dexter Wansel'),
('Hymn - Single',2019,NULL,'Rhye'),
('The Best 18',2002,NULL,'Децл'),
('GRAND Collection vol.2',2010,NULL,'Стас Михайлов'),
('18',2002,NULL,'Moby'),
('Body Language',2003,NULL,'Kylie Minogue'),
('Lisa Stansfield',1997,NULL,'Lisa Stansfield'),
('Emergency on Planet Earth',1993,NULL,'Jamiroquai'),
('Wild Ones',2012,NULL,'Flo Rida'),
('Black Sands',2010,true,'VARIOUS_ARTISTS'),
('#душнодует - Single',2020,NULL,'IOWA'),
('Chuck Berry is on Top',1959,NULL,'Chuck Berry'),
('Лучшие песни',2014,NULL,'Каста'),
('Booty (DaaHype Remix) (feat. Iggy Azalea) - Single',2014,true,'VARIOUS_ARTISTS'),
('Экспонат - Single',2016,true,'VARIOUS_ARTISTS'),
('Gridlock''d Soundtrack',1997,true,'VARIOUS_ARTISTS'),
('Газовая атака',1996,true,'VARIOUS_ARTISTS'),
('Ya Ya Ya Ya (Single)',2013,NULL,'Hande Yener'),
('The Greatest Hits',2006,true,'VARIOUS_ARTISTS'),
('Sehnsucht',1998,NULL,'Rammstein'),
('Metallica',1991,NULL,'Metallica'),
('Holding Onto Heaven (Remixes) (EP)',2014,NULL,'Foxes'),
('Brooklyn''s Don Diva',2008,NULL,'Foxy Brown'),
('1408',2009,NULL,'Кинг Стивен'),
('Kanatlarım Var Ruhumda - Single',2014,true,'VARIOUS_ARTISTS'),
('Champion Sound',2007,NULL,'Jaylib'),
('All We Got Iz Us',1995,NULL,'Onyx'),
('Soul Organic',1999,NULL,'Hil St. Soul'),
('Back in the Day',2000,NULL,'Courtney Pine'),
('The Party''s Over EP',2016,NULL,'Prophets of Rage'),
('Friends (Special Version) (feat. Rock Mafia) (Remixes) EP',2012,true,'VARIOUS_ARTISTS'),
('Can You Feel Me',1996,NULL,'Dru Down'),
('Drunk Groove - Single',2017,NULL,'MARUV & Boosin'),
('A Girl Like Me',2007,NULL,'Rihanna'),
('Iron Flag',2001,NULL,'Wu-Tang Clan'),
('Crunk Juice',2004,NULL,'Lil Jon & The East Side Boyz'),
('Mind the Moon',2019,NULL,'Milky Chance'),
('Floss Mode',1995,NULL,'The Govenor & House Reps'),
('Northern Star',1999,NULL,'Melanie C'),
('From South Africa to South Carolina',1974,NULL,'Gil Scott-Heron & Brian Jackson'),
('21',2011,NULL,'Adele'),
('El Niño',1998,NULL,'Def Squad'),
('Free Me',2004,NULL,'Emma Bunton'),
('Origins',2018,NULL,'Imagine Dragons'),
('Midnight Love',1982,NULL,'Marvin Gaye'),
('Hush or Howl',2014,NULL,'Black Pistol Fire'),
('Reload',1997,NULL,'Metallica'),
('Black Dialogue',2005,NULL,'The Perceptionists'),
('Sgt. Pepper''s Lonely Hearts Club Band',1967,NULL,'The Beatles'),
('Pillowfight',2004,NULL,'Pillowfight'),
('La La Land Soundtrack',2016,true,'VARIOUS_ARTISTS'),
('Elvis',1956,NULL,'Elvis Presley'),
('Act Like You Know',1991,NULL,'MC Lyte'),
('Crystal Castles II',2010,NULL,'Crystal Castles'),
('Once Upon a Time in America Soundtrack',1984,NULL,'Ennio Morricone'),
('The Unseen',2000,NULL,'Quasimoto'),
('Good Things',2010,NULL,'Aloe Blacc'),
('Us',1973,NULL,'Maceo'),
('Sex, Props, Cream... And the Drama in Between',1996,NULL,'Punk Barbarians'),
('For Those About to Rock (We Salute You)',1981,NULL,'AC/DC'),
('Маньяки',2001,NULL,'Дискотека Авария'),
('20 Greatest Motown Hits',1987,NULL,'Edwin Starr'),
('Eve-Olution',2002,NULL,'Eve'),
('All Eyez on Me: Book II',1996,NULL,'2Pac'),
('Expansion Team',2001,NULL,'Dilated Peoples'),
('No Nose Job: The Legend of Digital Underground',2001,NULL,'Digital Underground'),
('Champion Sound',2003,NULL,'Jaylib'),
('The New World Order',1996,NULL,'Poor Righteous Teachers'),
('Bosses Will Be Bosses',1999,NULL,'The Delinquents'),
('The New Classic',2014,NULL,'Iggy Azalea'),
('The Lateness of the Hour',2011,NULL,'Alex Clare'),
('Alsou',2001,NULL,'Алсу'),
('Baduizm',1997,NULL,'Erykah Badu'),
('With The Beatles',1963,NULL,'The Beatles'),
('My World',2009,NULL,'Lee Fields'),
('The Very Best of Sheryl Crow',2003,NULL,'Sheryl Crow'),
('T.I. Vs. T.I.P.',2007,NULL,'T.I.'),
('Crowded - Single',2013,NULL,'Ice Cube'),
('Pendulum',1970,NULL,'Creedence Clearwater Revival'),
('The Very Best of Big Daddy Kane',2001,NULL,'Big Daddy Kane'),
('Como Ama Una Mujer',2007,NULL,'Jennifer Lopez'),
('Souljaboytellem.com',2007,NULL,'Soulja Boy'),
('Hidden Beach Recordings Presents: Unwrapped, Vol. 1',2001,NULL,'Hidden Beach Recordings'),
('Holy Wood (In the Shadow of the Valley of Death)',2000,NULL,'Marilyn Manson'),
('Black Business',1993,NULL,'Poor Righteous Teachers'),
('Animal Magic',2001,NULL,'Bonobo'),
('Vicious Delicious',2007,NULL,'Infected Mushroom'),
('Bee Gees: Greatest',2007,true,'VARIOUS_ARTISTS'),
('One Of The Boys',2009,NULL,'Katy Perry'),
('52nd Street',1978,NULL,'Billy Joel'),
('I Pledge Alliance To The Grind II',2008,NULL,'Killer Mike'),
('25',2015,NULL,'Adele'),
('Drink the Sea',2010,true,'VARIOUS_ARTISTS'),
('By Your Side',2012,NULL,'Breakbot'),
('Celtic Dancer',2005,NULL,'Greg Joy'),
('Ross',1978,NULL,'Diana Ross'),
('Best Of',2010,NULL,'Nouvelle Vague'),
('The Anthology',1999,true,'VARIOUS_ARTISTS'),
('Super Hits',1998,NULL,'Blue Öyster Cult'),
('Supergirl EP',2015,NULL,'Anna Naklab'),
('Toy - Single',2018,NULL,'Netta'),
('Tourist',2000,NULL,'St. Germain'),
('Stankonia',2000,NULL,'Outkast'),
('Blood Like Lemonade',2010,NULL,'Morcheeba'),
('My Brother & Me',2004,NULL,'Ying Yang Twins'),
('Ofenbach',2019,NULL,'Ofenbach'),
('Outta Control EP',2005,NULL,'50 Cent'),
('Blue Foundation',2001,NULL,'Blue Foundation'),
('Desire',2007,NULL,'Pharoahe Monch'),
('Led Zeppelin IV',1971,NULL,'Led Zeppelin'),
('Enta Da Stage',1993,NULL,'Black Moon'),
('Мой любимый альбом',2011,NULL,'Jahmal TGK'),
('Your Domino (Acoustic) - Single',2017,NULL,'Jessie Ware'),
('Back in Business',1997,NULL,'EPMD'),
('Stone Cold Rhymin''',1989,NULL,'Young MC'),
('Flute Concertos Op. X',2014,NULL,'Antonio Vivaldi'),
('The Distance',1982,NULL,'Bob Seger & the Silver Bullet Band'),
('Toys in the Attic',1975,NULL,'Aerosmith'),
('Muttersprache',2015,NULL,'Sarah Connor'),
('Pieces of a Man',1971,NULL,'Gil Scott-Heron'),
('Forever Neverland',2018,NULL,'MØ'),
('By The Way',2002,NULL,'Red Hot Chili Peppers'),
('Convergence',2015,NULL,'Synapson'),
('Selfish Love (Acoustic) - Single',2017,NULL,'Jessie Ware'),
('Blood Sugar Sex Magik',1991,NULL,'Red Hot Chili Peppers'),
('The Motown Anthology',2009,NULL,'The Isley Brothers'),
('In a Special Way',1983,NULL,'DeBarge'),
('Onna wo Yametai Soshite',2010,NULL,'Meiko Kaji'),
('Ritual of the Savage',1951,NULL,'Les Baxter and His Orchestra'),
('Beyond Magnetic EP',2012,NULL,'Metallica'),
('Жу-Жу (feat. ST) - Single',2018,NULL,'Ленинград'),
('Cold as Ice',1999,true,'VARIOUS_ARTISTS'),
('Greatest Hits 1970-2002',2002,true,'VARIOUS_ARTISTS'),
('Faded',1994,NULL,'Don Jagwarr'),
('Diana & Marvin',1973,NULL,'Marvin Gaye & Diana Ross'),
('Check Your Head',1992,NULL,'Beastie Boys'),
('I Am',1979,NULL,'Earth, Wind & Fire'),
('The Best of Nickelback Volume 1',2013,NULL,'Nickelback'),
('Think Like a Girl',1997,NULL,'Diana King'),
('Elephunk',2003,NULL,'Black Eyed Peas'),
('Epigram',2016,NULL,'Gramatik'),
('The Complete Motown Singles, Vol. 2: 1962',2005,true,'VARIOUS_ARTISTS'),
('The Calling',2003,NULL,'Hilltop Hoods'),
('Stronger Than Pride',1988,NULL,'Sade'),
('Good Girl Gone Bad',2007,NULL,'Rihanna'),
('Back to Now',2012,NULL,'Skye'),
('Joanne',2016,NULL,'Lady Gaga'),
('Come Away With Me',2002,NULL,'Norah Jones'),
('Goon',2015,NULL,'Tobias Jesso Jr.'),
('The Wanderings of the Avener',2015,true,'VARIOUS_ARTISTS'),
('Glorious',2014,NULL,'Foxes'),
('Midas Touch - Single',2019,NULL,'Slick Rick'),
('Tronic',2008,NULL,'Black Milk'),
('The MF Life',2012,NULL,'Melanie Fiona'),
('Finding Forever',2007,NULL,'Common'),
('Americana',1998,NULL,'The Offspring'),
('The Betrayal',1996,NULL,'Nutt-So'),
('Come to Daddy EP',1997,NULL,'Aphex Twin'),
('Food',2014,NULL,'Kelis'),
('Signed and Sealed in Blood',2013,NULL,'Dropkick Murphys'),
('Lunitik Muzik',1997,NULL,'Luniz'),
('Сопротивление (EP)',2015,NULL,'Порнофильмы'),
('LA Confidential Presents Knoc-Turn''al - EP',2002,true,'VARIOUS_ARTISTS'),
('The Very Best Of',1990,NULL,'Kool & The Gang'),
('Stuntman',1979,NULL,'Edgar Froese'),
('Use Your Illusion II',1991,NULL,'Guns N'' Roses'),
('Untitled',2008,NULL,'Nas'),
('The Essential',2003,NULL,'Thelonious Monk'),
('It Was Written',1996,NULL,'Nas'),
('Назад в СССР',2009,NULL,'Цветы'),
('E.G.O.',2018,NULL,'Jah Khalib'),
('Here Come the Lords',1993,NULL,'Lords of the Underground'),
('Most Known Unknown',2005,NULL,'Three 6 Mafia'),
('The Lion The Beast The Beat',2012,NULL,'Grace Potter & The Nocturnals'),
('Get Mashed!',2005,NULL,'Morcheeba'),
('Remixed & Reimagined',2015,NULL,'Nina Simone'),
('Take a Look Over Your Shoulder (Reality)',1997,NULL,'Warren G'),
('Expect the Unexpected',2019,NULL,'Tracey Lee'),
('Life on Mars',1976,NULL,'Dexter Wansel'),
('Flute Quintets, Op. 7 Nos. 3-6',1998,NULL,'Johann Christian Cannabich'),
('Guilty',1980,NULL,'Barbra Streisand'),
('The Fame',2008,NULL,'Lady Gaga'),
('OSLO (gets cold this time of year) - Single',2018,NULL,'Charlotte Qvale'),
('Whoa, Nelly!',2000,NULL,'Nelly Furtado'),
('После шоу',2016,NULL,'Lenin & Карандаш'),
('Stolen Dance EP',2014,NULL,'Milky Chance'),
('Mecca and the Soul Brother',1992,NULL,'Pete Rock & C.L. Smooth'),
('Tha Blue Carpet Treatment',2006,NULL,'Snoop Dogg'),
('Better Dayz',2002,NULL,'2Pac'),
('Word of Mouf',2001,NULL,'Ludacris'),
('The Complete Greatest Hits',2003,NULL,'Eagles'),
('I Can''t Stand Still',1982,NULL,'Don Henley'),
('Seven Seas',2015,NULL,'Emancipator'),
('Ruin My Life - Single',2018,NULL,'Zara Larsson'),
('#людимаяки',2020,NULL,'IOWA'),
('A Bit of Liverpool',1964,NULL,'The Supremes'),
('Travelling Like the Light',2009,NULL,'VV Brown'),
('Mixed Race',2010,NULL,'Tricky'),
('Once Upon a Time in Hollywood Soundtrack',2019,true,'VARIOUS_ARTISTS'),
('A/B',2016,NULL,'Kaleo'),
('Westworld: Season 1 Soundtrack',2016,true,'VARIOUS_ARTISTS'),
('Son Rise Vol. 1',2004,NULL,'Yaki Kadafi'),
('The End of the Innocence',1989,NULL,'Don Henley'),
('Still I Rise',1999,NULL,'2Pac & The Outlawz'),
('C U When U Get There (CDS)',1997,NULL,'Coolio'),
('Rare Tracks',1998,NULL,'Pete Rock & C.L. Smooth'),
('The Family Jewels',2010,NULL,'Marina & The Diamonds'),
('There Were Tears (Single)',2016,NULL,'Imany'),
('The Very Best of Sister Sledge 1973-93',1993,NULL,'Sister Sledge'),
('One Thing Right - Single',2019,NULL,'Marshmello & Kane Brown'),
('Scars & Souvenirs',2008,NULL,'Theory of a Deadman'),
('Blue Lines',1991,NULL,'Massive Attack'),
('King of Rock',1985,NULL,'Run-D.M.C.'),
('keepers of the Funk',1994,NULL,'Lords of the Underground'),
('Экстаз - Single',2017,NULL,'Ленинград'),
('Нищая Страна',2013,NULL,'Порнофильмы'),
('Nessie',2013,NULL,'8-Bitchin’tendo'),
('The Worlds Greatest Entertainer',1988,NULL,'Doug E. Fresh & The Get Fresh Crew'),
('Пуля-дура - Single',2019,NULL,'Loboda'),
('The Shape of a Broken Heart',2011,NULL,'Imany'),
('Many Stylez',2006,NULL,'Sofa'),
('Jazz Moods: Cool',2004,NULL,'Grover Washington, Jr.'),
('Lily Was Here (CDM)',1989,NULL,'David A. Stewart & Candy Dulfer'),
('Thickfreakness',2003,NULL,'The Black Keys'),
('Tougher Than Love',1995,NULL,'Diana King'),
('Future',2017,true,'VARIOUS_ARTISTS'),
('At the Speed of Life',1996,NULL,'Xzibit'),
('Американщина III',2020,NULL,'Карандаш'),
('Sorry Not Sorry - Single',2017,NULL,'Demi Lovato'),
('Building the Perfect Beast',1984,NULL,'Don Henley'),
('Switch - Single',2017,NULL,'Iggy Azalea'),
('When Life Gives You Lemons, You Paint That Shit Gold',2008,NULL,'Atmosphere'),
('Pump',1989,NULL,'Aerosmith'),
('The Score',1996,NULL,'Fugees'),
('ATLiens',1996,NULL,'OutKast'),
('Can''t Dance To a Track That Ain''t Got No Soul - Single',2019,NULL,'Slick Rick'),
('Ultraviolence',2014,NULL,'Lana Del Rey'),
('Скучная Жизнь',2012,NULL,'Порнофильмы'),
('Y?N-Vee',1994,NULL,'Y?N-Vee'),
('Gold Cobra',2011,NULL,'Limp Bizkit'),
('Massive Attack (ft. Sean Garrett) - Single',2010,NULL,'Nicki Minaj'),
('The Album',1997,NULL,'The Firm'),
('Evolve',2017,NULL,'Imagine Dragons'),
('Looking for the Perfect Beat: 1980-1985',2001,NULL,'Afrika Bambaataa'),
('Queen',2018,NULL,'Nicki Minaj'),
('Back for the First Time',2000,NULL,'Ludacris'),
('Big Calm',1998,NULL,'Morcheeba'),
('Til The Casket Drops',2012,NULL,'ZZ Ward'),
('The Black Bossalini (aka Dr. Bomb From Da Bay)',1997,NULL,'Spice 1'),
('E•MO•TION',2015,NULL,'Carly Rae Jepsen'),
('Booty (Vice Remix) (feat. Iggy Azalea) - Single',2014,true,'VARIOUS_ARTISTS'),
('Trip The Light Fantastic',2007,NULL,'Sophie Ellis-Bextor'),
('О мышах и людях. Жемчужина',2004,true,'VARIOUS_ARTISTS'),
('Лучшие песни. Часть II',2008,NULL,'Михаил Шуфутинский'),
('Back in Black',1980,NULL,'AC/DC'),
('Ironman',1996,NULL,'Ghostface Killah'),
('Messenger of the Gods: The Singles',2016,true,'VARIOUS_ARTISTS'),
('I Ain''t Movin''',1994,NULL,'Des''Ree'),
('По реке',2006,NULL,'Krec'),
('The Good, The Bad and The Ugly Soundtrack',1966,NULL,'Ennio Morricone'),
('Wanderlust',2014,NULL,'Sophie Ellis-Bextor'),
('Funkdafied',1994,NULL,'Da Brat'),
('Трое в лодке, не считая собаки',2007,NULL,'Джером Джером Клапка'),
('Midnight (Acoustic) - Single',2017,NULL,'Jessie Ware'),
('Synkronized',1999,NULL,'Jamiroquai'),
('Way 2 Fonky',1992,NULL,'DJ Quik'),
('Coco',2009,NULL,'Parov Stelar'),
('Badder Than B Fore (The Remix Album)',1997,NULL,'MC Lyte'),
('Just Another Day in Paradise',1982,NULL,'Bertie Higgins'),
('Legend',2015,NULL,'MC Lyte'),
('Break Up',2009,NULL,'Pete Yorn & Scarlett Johansson'),
('Highway To Hell',1979,NULL,'AC/DC'),
('Still on My Mind',2019,NULL,'Dido'),
('6 Brandenburgische Konzerte, 4 Oüverturen, Tripelkonzert BWV 1044',2002,NULL,'Johann Sebastian Bach'),
('War & Peace Vol. 1 (The War Disc)',1998,NULL,'Ice Cube'),
('W.A.R. (We Are Renegades)',2011,NULL,'Pharoahe Monch'),
('Dusk to Dawn',2013,NULL,'Emancipator'),
('Aloha From Hawaii Via Satellite',1973,NULL,'Elvis Presley'),
('Return to the 36 Chambers',1995,NULL,'Ol'' Dirty Bastard'),
('Dogg Chit',2007,NULL,'Tha Dogg Pound'),
('R & G (Rhythm & Gangsta) The Masterpiece',2004,NULL,'Snoop Dogg'),
('MTV Unplugged in New York',1994,NULL,'Nirvana'),
('1992',2016,true,'VARIOUS_ARTISTS'),
('Flames - Single',2018,NULL,'David Guetta & Sia'),
('Sir Lucious Left Foot: The Son of Chico Dusty',2010,NULL,'Big Boi'),
('Efil4zaggin',1991,NULL,'N.W.A'),
('We''re All Somebody from Somewhere',2016,NULL,'Steven Tyler'),
('Unapologetic',2012,NULL,'Rihanna'),
('Illegal Business?',1993,NULL,'Mac Mall'),
('Pink Friday',2010,NULL,'Nicki Minaj'),
('Life After Death',1997,NULL,'The Notorious B.I.G.'),
('Gangnam Style - Single',2012,true,'VARIOUS_ARTISTS'),
('Richie Rich Presents: Grab, Snatches & Takes',2004,true,'VARIOUS_ARTISTS'),
('TP',1980,NULL,'Teddy Pendergrass'),
('Dig Your Own Hole',1997,NULL,'The Chemical Brothers'),
('Gimme Shelter',1970,NULL,'Merry Clayton'),
('Regulate (CDM)',1994,true,'VARIOUS_ARTISTS'),
('On and On (Single)',2000,NULL,'Pain'),
('Kaleo',2013,NULL,'Kaleo'),
('Elvis'' Golden Records (Volume 1)',1958,NULL,'Elvis Presley'),
('Feed the Machine',2017,true,'VARIOUS_ARTISTS'),
('Beg for Mercy',2003,NULL,'G-Unit'),
('Loose',2006,NULL,'Nelly Furtado'),
('Aquarius',2014,true,'VARIOUS_ARTISTS'),
('S&M',1999,NULL,'Metallica'),
('I Don''t Know Why (feat. Mayer Hawthorne) - Single',2016,NULL,'Kraak & Smaak'),
('I Am',2007,NULL,'Chrisette Michele'),
('It''s Probably Me CDS',1992,NULL,'Sting'),
('Blakroc',2009,NULL,'Blakroc'),
('Light My Body Up (feat. Nicki Minaj & Lil Wayne) - Single',2017,true,'VARIOUS_ARTISTS'),
('Something Wicked This Way Comes',2002,NULL,'The Herbaliser'),
('Modjo',2001,NULL,'Modjo'),
('Shoot From The Hip',2003,NULL,'Sophie Ellis-Bextor'),
('El Camino',2011,NULL,'The Black Keys'),
('The Element of Freedom',2009,NULL,'Alicia Keys'),
('A Funk Odyssey',2001,NULL,'Jamiroquai'),
('...And Then There Was X',1999,NULL,'DMX'),
('Aquemini',1998,NULL,'OutKast'),
('Soul Deep',2009,true,'VARIOUS_ARTISTS'),
('Rearviewmirror (Greatest Hits 1991-2003)',2004,true,'VARIOUS_ARTISTS'),
('Beginnings: The Lost Tapes 1988-1991',2007,NULL,'2Pac'),
('The Don Killuminati: The 7 Day Theory',1996,NULL,'Makaveli'),
('Bulletproof Wallets',2001,NULL,'Ghostface Killah'),
('The Ultimate Collection',2002,NULL,'The Kinks'),
('7',2019,NULL,'Макс Барских'),
('We Can''t Be Stopped',1991,NULL,'Geto Boys'),
('For a Few Dollars More Soundtrack',1965,NULL,'Ennio Morricone'),
('Riders on the Storm (Fredwreck Remix) - Single',2007,true,'VARIOUS_ARTISTS'),
('This Beautiful Life',1999,NULL,'Big Bad Voodoo Daddy'),
('The Complete Motown Singles, Vol. 1: 1959-1961',2004,true,'VARIOUS_ARTISTS'),
('Carpe Diem',1995,NULL,'Lara Fabian'),
('Blaze Away',2018,NULL,'Morcheeba'),
('Breath of Heaven: A Holiday Collection',1997,NULL,'Grover Washington, Jr.'),
('Make it Big',1984,NULL,'Wham!'),
('GRAND Collection vol.1',2010,NULL,'Сергей Трофимов'),
('MEGATRON - Single',2019,NULL,'Nicki Minaj'),
('Secrets',1996,NULL,'Toni Braxton'),
('200 по встречной',2006,NULL,'t.A.T.u.'),
('Back to Black',2007,true,'VARIOUS_ARTISTS'),
('II',1994,NULL,'Boyz II Men'),
('Real Love',1991,NULL,'Lisa Stansfield'),
('Anima',2015,NULL,'Francesca Belmonte'),
('The Return of the Regulator',2001,NULL,'Warren G'),
('Hell on Earth',1996,NULL,'Mobb Deep'),
('Toto',1978,NULL,'Toto'),
('2525 (Exordium & Terminus)',1969,NULL,'Zager & Evans'),
('FRIENDS - Single',2018,NULL,'Marshmello & Anne-Marie'),
('The Greatest Hits',2012,NULL,'3 Doors Down'),
('Ahmad',1994,NULL,'Ahmad'),
('÷',2017,true,'VARIOUS_ARTISTS'),
('The Invisible Girl',2013,NULL,'Parov Stelar Trio'),
('Introducing Joss Stone',2007,NULL,'Joss Stone'),
('Искусство побеждать (Искусство войны)',2015,NULL,'Сунь-Цзы'),
('God Gave Me Everything - Single',2001,NULL,'Mick Jagger'),
('Straight Up Sewaside',1993,NULL,'Das EFX'),
('Woman',2013,NULL,'Rhye'),
('The Definitive Collection',2006,NULL,'Steely Dan'),
('So Good',2017,NULL,'Zara Larsson'),
('Battle of the Sexes',2010,NULL,'Ludacris'),
('Herzeleid',1995,NULL,'Rammstein'),
('Supreme Beings of Leisure',2000,NULL,'Supreme Beings of Leisure'),
('A Million Voices (Eurovision 2015 - Russia) - Single',2015,true,'VARIOUS_ARTISTS'),
('Пьяное солнце - Single',2015,true,'VARIOUS_ARTISTS'),
('Loving You',1957,NULL,'Elvis Presley'),
('Ain''t Nobody Worryin''',2005,NULL,'Anthony Hamilton'),
('The Wonderful World Of Christmas',1971,NULL,'Elvis Presley'),
('Swass',1988,NULL,'Sir Mix-A-Lot'),
('Greatest Hits: The Atlantic Years',2006,true,'VARIOUS_ARTISTS'),
('SuperSTAR - Single',2018,NULL,'Loboda'),
('When We All Fall Asleep, Where Do We Go?',2019,NULL,'Billie Eilish'),
('Audio, Video, Disco.',2011,true,'VARIOUS_ARTISTS'),
('The Mouse and The Mask',2005,NULL,'DANGERDOOM'),
('Never Really Over - Single',2019,NULL,'Katy Perry'),
('Arc of a Diver',1980,NULL,'Steve Winwood'),
('Conspiracy Remixes',2011,NULL,'Gesaffelstein'),
('Сиськи - Single',2016,true,'VARIOUS_ARTISTS'),
('Gran Turismo',1998,NULL,'The Cardigans'),
('На Всех Экранах Страны (EP)',2012,NULL,'Порнофильмы'),
('Spirit',1976,NULL,'Earth, Wind & Fire'),
('I Wish My Brother George Was Here',1991,NULL,'Del Tha Funkee Homosapien'),
('We Are Young Money',2009,NULL,'Young Money'),
('ThisIsMe Then: The Best of Common',2007,NULL,'Common'),
('Calm Ocean',2008,NULL,'David Sun'),
('Down to Earth',1996,NULL,'Grav'),
('The Burning Spider',2017,NULL,'Parov Stelar'),
('Cantatas BWV 54 & 170',2011,NULL,'Johann Sebastian Bach'),
('The Big Knock',2014,true,'VARIOUS_ARTISTS'),
('The Return of the Space Cowboy',1995,NULL,'Jamiroquai'),
('What''s Going On',1971,NULL,'Marvin Gaye'),
('The Donnas Turn 21',2001,NULL,'The Donnas'),
('Bayou Country',1969,NULL,'Creedence Clearwater Revival'),
('Граф Монте-Кристо',2013,NULL,'Дюма Александр'),
('Laugh Now, Cry Later',2006,NULL,'Ice Cube'),
('A Prince in Exile',2002,NULL,'Ray Luv'),
('The Bodyguard Soundtrack',1992,true,'VARIOUS_ARTISTS'),
('The Fame Monster',2009,NULL,'Lady Gaga'),
('Full Clip: A Decade of Gang Starr',1999,NULL,'Gang Starr'),
('TGK AK47',2016,NULL,'Триагрутрика и AK-47'),
('Singles',2015,NULL,'Maroon 5'),
('Closer ',1980,NULL,'Joy Division'),
('Town Bidness, vol. 2',2011,NULL,'Richie Rich'),
('Это Пройдёт',2020,NULL,'Порнофильмы'),
('Fantastic Voyage: The Greatest Hits',2001,NULL,'Coolio'),
('Prism',2013,true,'VARIOUS_ARTISTS'),
('Hand on the Torch',1993,NULL,'Us3'),
('NIghtwatch',1978,NULL,'Kenny Loggins'),
('Warriorz',2000,NULL,'M.O.P.'),
('Elvis: As Recorded at Madison Square Garden',1972,NULL,'Elvis Presley'),
('Дальше',2008,NULL,'Звери'),
('Here I Come',1985,NULL,'Barrington Levy'),
('The DeBarges',1981,NULL,'DeBarge'),
('Aerosmith',1973,NULL,'Aerosmith'),
('My Beautiful Dark Twisted Fantasy',2010,NULL,'Kanye West'),
('Tuxedo III',2019,NULL,'Tuxedo'),
('Tu Veneno',2000,NULL,'Natalia Oreiro'),
('Still Writing in My Diary: 2nd Entry',2004,NULL,'Petey Pablo'),
('Спасибо - Single',2011,true,'VARIOUS_ARTISTS'),
('Nimrod',1997,NULL,'Green Day'),
('Black Pistol Fire',2011,NULL,'Black Pistol Fire'),
('A Star is Born Soundtrack',2018,true,'VARIOUS_ARTISTS'),
('USA (United State of Atlanta)',2005,NULL,'Ying Yang Twins'),
('Swalla (feat. Nicki Minaj & Ty Dolla $ign) - Single',2017,true,'VARIOUS_ARTISTS'),
('Love. Angel. Music. Baby.',2004,NULL,'Gwen Stefani'),
('Free Will',1972,NULL,'Gil Scott-Heron'),
('First Band on the Moon',1996,NULL,'The Cardigans'),
('Madvillainy',2004,NULL,'Madvillain'),
('Mozart: Requiem',1987,NULL,'Wolfgang Amadeus Mozart'),
('Back to Basics',2006,NULL,'Christina Aguilera'),
('В Диапазоне Между Отчаянием и Надеждой',2017,NULL,'Порнофильмы'),
('Explicit Game',1994,NULL,'Dru Down'),
('Soul Box',1973,NULL,'Grover Washington, Jr.'),
('All My Tomorrows',1994,NULL,'Grover Washington, Jr.'),
('Lifestylez Ov Da Poor & Dangerous',1995,NULL,'Big L'),
('Awake',2014,NULL,'Tycho'),
('Late Night Feelings',2019,NULL,'Mark Ronson'),
('The Dock Of The Bay - The Definitive Collection',1992,NULL,'Otis Redding'),
('Party of One EP',2016,NULL,'Mayer Hawthorne'),
('Hold It Down',1995,NULL,'Das EFX'),
('Hear My Cry',2000,NULL,'Sonique'),
('Kelis Was Here',2006,NULL,'Kelis'),
('Всякое',2018,NULL,'Ленинград'),
('Thug Life: Vol. 1',1994,NULL,'Thug Life'),
('Tuesday (feat. Danelle Sandoval) - Single',2016,NULL,'Burak Yeter'),
('Потому что нельзя быть красивой такой',1998,NULL,'Белый Орел'),
('Golden Arms Redemption',1999,NULL,'U-God'),
('Welcome to Cali',2006,NULL,'Double F. & J. Dilla'),
('Music',2000,NULL,'Madonna'),
('Space Boogie: Smoke Oddessey',2001,NULL,'Kurupt'),
('Rated R',2009,NULL,'Rihanna'),
('Super Trouper',1980,NULL,'ABBA'),
('Streets of Compton',2016,NULL,'The Game'),
('The Greatest Hits Vol.1',2008,NULL,'Noize MC'),
('Hozier',2014,NULL,'Hozier'),
('Straight Outta Compton',1988,NULL,'N.W.A'),
('Sadeness, Pt. I - EP',1990,true,'VARIOUS_ARTISTS'),
('Modern Day Jazz Stories',1995,NULL,'Courtney Pine'),
('Disposable Arts',2001,NULL,'Masta Ace'),
('In My Defense',2019,NULL,'Iggy Azalea'),
('Гравитация',2015,NULL,'Интарс Бусулис'),
('The Fat of the Land',1997,NULL,'The Prodigy'),
('Born Again',1999,NULL,'The Notorious B.I.G.'),
('Demain',2019,NULL,'Amel Bent'),
('Weather',2019,NULL,'Tycho'),
('The 50 Greatest Pieces of Classical Music',2009,true,'VARIOUS_ARTISTS'),
('Between a Rock and a Hard Place',1994,NULL,'Artifacts'),
('Maxwell''s Urban Hang Suite',1996,NULL,'Maxwell'),
('Ultra',1997,NULL,'Depeche Mode'),
('Remixed',2008,NULL,'Alicia Keys'),
('Whut? Thee Album',1992,NULL,'Redman'),
('Мысленный волк',2014,NULL,'Смысловые галлюцинации'),
('Kill at Will EP',1990,NULL,'Ice Cube'),
('Злой гений Нью-Йорка',2015,NULL,'Ван Дайн Стивен'),
('Agapé',2019,NULL,'Shy''m'),
('Au Au - Single',2019,NULL,'Filatov & Karas'),
('Смерть на рэйве',1999,NULL,'Кирпичи'),
('In Stereo',1999,NULL,'Bomfunk MC''s'),
('Fishscale',2006,NULL,'Ghostface Killah'),
('Русская мечта. Часть 1',2015,NULL,'Порнофильмы'),
('Смелость не нравиться. Как полюбить себя, найти свое призвание и выбрать счастье',2019,NULL,'Кишими Ичиро; Каго Фумитаке'),
('Let''s Rock',2019,NULL,'The Black Keys'),
('Music for the People',1991,NULL,'Marky Mark & The Funky Bunch'),
('Лучшие песни',2008,NULL,'Гости из будущего'),
('Восставший из Ада',2000,true,'VARIOUS_ARTISTS'),
('Second Helping',1974,NULL,'Lynyrd Skynyrd'),
('New Old Songs',2001,NULL,'Limp Bizkit'),
('Both Sides of the Brain',2000,NULL,'Del Tha Funkee Homosapien'),
('Me & My Brother',2003,NULL,'Ying Yang Twins'),
('Grand Champ',2003,NULL,'DMX'),
('Powerage',1978,NULL,'AC/DC'),
('Blacks and Blues',1973,NULL,'Bobbi Humphrey'),
('Let The Rhythm Hit ''Em',1990,NULL,'Eric B. & Rakim'),
('The Big Badass',1994,NULL,'Ant Banks'),
('Three',2003,NULL,'Sugababes'),
('Spend the Night',2002,NULL,'The Donnas'),
('Greatest Hits Vol. 16',2009,NULL,'The Donnas'),
('Internal Affairs',1999,NULL,'Pharoahe Monch'),
('Bad to the Bone',1992,NULL,'Inner Circle'),
('This is What the Truth Feels Like',2016,NULL,'Gwen Stefani'),
('Seven',1974,NULL,'Bob Seger'),
('R U Still Down? [Remember Me]',1997,NULL,'2Pac'),
('Skyfall - Single',2012,NULL,'Adele'),
('Unorthodox Jukebox',2012,NULL,'Bruno Mars'),
('Return of Saturn',2000,NULL,'No Doubt'),
('Triforce Tunes 2nd Level',2016,true,'VARIOUS_ARTISTS'),
('Chicken-N-Beer',2003,NULL,'Ludacris'),
('G I R L',2014,NULL,'Pharrell Williams'),
('Coolaid',2016,NULL,'Snoop Dogg'),
('T.H.U.G.S.',2007,NULL,'Bone Thugs-N-Harmony'),
('Songs in a Minor',2001,NULL,'Alicia Keys'),
('Laura Vane & The Vipertones',2009,NULL,'Laura Vane & The Vipertones'),
('Souvenirs',1975,NULL,'Demis Roussos'),
('Stars: The Best of the Cranberries 1992-2002',2002,true,'VARIOUS_ARTISTS'),
('Dynamite',2005,NULL,'Jamiroquai'),
('Life for Rent',2003,NULL,'Dido'),
('The Resistance',2009,NULL,'Muse'),
('Don''t Look Any Further',1984,NULL,'Dennis Edwards'),
('Born This Way',2011,NULL,'Lady Gaga'),
('Bad Intentions CDM',2001,NULL,'Dr. Dre'),
('Nigga Please',1999,NULL,'Ol'' Dirty Bastard'),
('Strawberry Moon',1987,NULL,'Grover Washington, Jr.'),
('This Week',2004,NULL,'Jean Grae'),
('Demon Days',2005,NULL,'Gorillaz'),
('Pure Poverty',1991,NULL,'Poor Righteous Teachers'),
('Beyond Hamsterdam: Baltimore Tracks from The Wire',2008,true,'VARIOUS_ARTISTS'),
('Everyday is Christmas',2017,true,'VARIOUS_ARTISTS'),
('Come Morning',1981,NULL,'Grover Washington, Jr.'),
('Forest',2001,NULL,'David Sun'),
('Be',2005,NULL,'Common'),
('Enter The Wu-Tang (36 Chambers)',1993,NULL,'Wu-Tang Clan'),
('Black ''N Dangerous',1996,NULL,'Young Lay'),
('I Wanna Thank Me',2019,NULL,'Snoop Dogg'),
('1000 Forms of Fear',2014,true,'VARIOUS_ARTISTS'),
('This is America - Single',2018,NULL,'Childish Gambino'),
('Golden Hour',2018,NULL,'Kacey Musgraves'),
('2nd II None',1991,NULL,'2nd II None'),
('Cherry',2005,NULL,'Lisa Shaw'),
('E=MC²',2007,NULL,'Mariah Carey'),
('The Man with the Iron Fists Soundtrack',2012,true,'VARIOUS_ARTISTS'),
('Ultimate Santana',2007,NULL,'Santana'),
('The Best of Chic: Volume 2',1992,NULL,'Chic'),
('Everything Not Saved Will Be Lost - Part 1',2019,NULL,'Foals'),
('God''s Son',2002,NULL,'Nas'),
('China',1979,NULL,'Vangelis'),
('Tasty',2003,NULL,'Kelis'),
('Избранное II',1996,NULL,'Сектор Газа'),
('The Bluebird Recordings: 1937-1938',1997,NULL,'Sonny Boy Williamson'),
('Witness',2017,NULL,'Katy Perry'),
('Dirt EP',2012,NULL,'8-BITchin’tendo'),
('Keeping Secrets',2009,NULL,'Skye'),
('Лучшее',2009,NULL,'Елена Ваенга'),
('Put Yo Hood Up',2001,NULL,'Lil Jon & The East Side Boyz'),
('Angels with Dirty Faces',1998,true,'VARIOUS_ARTISTS'),
('Pac''s Life',2006,NULL,'2Pac'),
('Ballbreaker',1995,NULL,'AC/DC'),
('Neighborhood Watch',2004,NULL,'Dilated Peoples'),
('Get Your Wings',1974,NULL,'Aerosmith'),
('Super Hits',1970,NULL,'Marvin Gaye'),
('Blood Eagle',2015,NULL,'Sabrepulse'),
('Billie-Eve',2011,NULL,'Ayo'),
('Funky Beat: The Best of Whodini',2006,NULL,'Whodini'),
('Poe Little Rich Girl',2004,NULL,'Jacki-O'),
('Mr. & Mrs. Smith Soundtrack',2005,true,'VARIOUS_ARTISTS'),
('Neva Again',1993,NULL,'Kam'),
('Wicked Games (feat. Anna Naklab) - Single',2013,NULL,'Parra for Cuva'),
('Vinyl #1',2019,NULL,'Zivert'),
('Neva Left',2017,true,'VARIOUS_ARTISTS'),
('Молодость и Панк-Рок',2014,NULL,'Порнофильмы'),
('Remedies',1995,NULL,'The Herbaliser'),
('The Best of Depeche Mode, Vol. 1',2006,true,'VARIOUS_ARTISTS'),
('It''s On (Dr. Dre) 187um Killa',1993,NULL,'Eazy-E'),
('The Downward Spiral',1994,NULL,'Nine Inch Nails'),
('Dookie',1994,NULL,'Green Day'),
('The Poison',2006,NULL,'Bullet for My Valentine'),
('INSTADRAMA - Single',2018,NULL,'Loboda'),
('Afro Temple',1973,NULL,'Sabu Martinez'),
('Liberation Transmission',2006,NULL,'Lostprophets'),
('Sweep of Days',2004,NULL,'Blue Foundation'),
('Minutes to Midnight',2007,true,'VARIOUS_ARTISTS'),
('No.6 Collaborations Project',2019,NULL,'Ed Sheeran'),
('The Red Light District',2004,NULL,'Ludacris'),
('Сила ума',2002,NULL,'Кирпичи'),
('Run Up (feat. PARTYNEXTDOOR & Nicki Minaj) - Single',2017,NULL,'Major Lazer'),
('I Need a Doctor (feat. Eminem & Skylar Grey) - Single',2011,NULL,'Dr. Dre'),
('Death Certificate',1991,NULL,'Ice Cube'),
('Нет волшебства',2004,NULL,'Krec'),
('Просто о важном',2016,NULL,'Леонид Агутин'),
('The Princess',2012,NULL,'Parov Stelar'),
('Protection',1994,NULL,'Massive Attack'),
('Hot Sauce Committee Part Two',2011,NULL,'Beastie Boys'),
('Shapes of Rhythm',1966,NULL,'Galt MacDermot'),
('American Life',2003,NULL,'Madonna'),
('Natalia Oreiro',2001,NULL,'Natalia Oreiro'),
('A Secret Place',1976,NULL,'Grover Washington, Jr.'),
('The Lion King',1994,true,'VARIOUS_ARTISTS'),
('Dangerously in Love',2003,NULL,'Beyoncé'),
('Vicious Lies and Dangerous Rumors',2012,NULL,'Big Boi'),
('Keepers of the Funk',1994,NULL,'Lords of the Underground'),
('No Roots - EP',2017,NULL,'Alice Merton'),
('Shy - Single',2018,true,'VARIOUS_ARTISTS'),
('Revelations',2006,NULL,'Audioslave'),
('Anywhere I Lay My Head',2008,NULL,'Scarlett Johansson'),
('That''s the Way of the World',1975,NULL,'Earth, Wind & Fire'),
('Off Parole',1996,NULL,'Rappin'' 4-Tay'),
('This is Me... Then',2002,NULL,'Jennifer Lopez'),
('The Song Diaries',2019,NULL,'Sophie Ellis-Bextor'),
('Anakonda A.K.A. "Benny Ill"',2001,NULL,'Akinyele'),
('If It Don''t Kill You, It Just Makes You Stronger',1989,NULL,'Bruce Willis'),
('Out of Exile',2005,NULL,'Audioslave'),
('Theater of the Mind',2008,NULL,'Ludacris'),
('Живи быстро, умри молодым',2010,NULL,'Карандаш'),
('Don''t Sweat the Technique',1992,NULL,'Eric B. & Rakim'),
('Монстр',2015,NULL,'Карандаш'),
('Raw Footage',2008,NULL,'Ice Cube'),
('Who Can You Trust?',1996,NULL,'Morcheeba'),
('An Innocent Man',1983,NULL,'Billy Joel'),
('Падай - Single',2018,NULL,'IOWA'),
('Skylarkin''',1980,NULL,'Grover Washington, Jr.'),
('Total Life Forever',2010,NULL,'Foals'),
('ABBA',1975,NULL,'ABBA'),
('Ленинград: Лучшее!',2014,true,'VARIOUS_ARTISTS'),
('Says Hello EP',2004,NULL,'Sabrepulse'),
('Views',2016,true,'VARIOUS_ARTISTS'),
('Sinatra: Best of the Best',2011,NULL,'Frank Sinatra'),
('Streams of Thought Vol. 1',2018,NULL,'Black Thought'),
('Django Unchained Soundtrack',2012,true,'VARIOUS_ARTISTS'),
('Deltron 3030',2000,NULL,'Deltron 3030'),
('Hair of the Dog',1975,NULL,'Nazareth'),
('Turbo City',2008,NULL,'Sabrepulse'),
('All Hands on Deck (Remix) (feat. Iggy Azalea) - Single',2015,true,'VARIOUS_ARTISTS'),
('Ventura',2019,NULL,'Anderson .Paak'),
('In a Major Way',1995,NULL,'E-40'),
('Head Up High',2013,NULL,'Morcheeba'),
('Цветы. Группа Стаса Намина. 1972-1979',1995,NULL,'Цветы'),
('Graduation',2007,NULL,'Kanye West'),
('Superdream',2019,NULL,'Big Wild'),
('Liberation',2018,NULL,'Christina Aguilera'),
('50 For 50',2018,NULL,'Jethro Tull'),
('Sugarhill Gang',1980,NULL,'The Sugarhill Gang'),
('She''s in Control',2004,NULL,'Chromeo'),
('H.N.I.C. Pt. 2',2008,NULL,'Prodigy of Mobb Deep'),
('Pronounced ''leh -''nerd-''skin-''nerd''',1973,NULL,'Lynyrd Skynyrd'),
('Back to the Future Score',1985,NULL,'Alan Silvestri'),
('Love + War',2015,true,'VARIOUS_ARTISTS'),
('Soul Impressions',1975,NULL,'Janko Nilovic'),
('Chipbreak Wars',2006,NULL,'Sabrepulse'),
('The Documentary',2005,NULL,'The Game'),
('Amerikkka''s Nightmare',1994,NULL,'Spice 1'),
('Westworld Season 2 Soundtrack',2018,NULL,'Ramin Djawadi'),
('All Trap Music',2013,true,'VARIOUS_ARTISTS'),
('Friendly Fire',2008,NULL,'Ariano'),
('Dvořák: Symphonies Nos. 7, 8, 9',1995,NULL,'Antonín Dvořák'),
('Flute Concertos',2009,NULL,'Ignaz Holzbauer'),
('Street Certified',2014,NULL,'M.O.P.'),
('Big Baller',1995,NULL,'MC Breed'),
('Element Eighty',2003,NULL,'Element Eighty'),
('Fly 2 (feat. NILETTO) - Single',2020,NULL,'Zivert'),
('Doo-Wops & Hooligans',2010,NULL,'Bruno Mars'),
('Green River',1969,NULL,'Creedence Clearwater Revival'),
('Speakerboxxx / The Love Below',2003,NULL,'Outkast'),
('Paradise EP',2012,NULL,'Lana Del Rey'),
('Mambo!',1954,NULL,'Yma Sumac'),
('Sing Motown',1967,NULL,'The Supremes'),
('Soul Strike!',2001,NULL,'Calypso King & The Soul Investigators'),
('Finding Beauty in the Wretched',2007,NULL,'Dirty Elegance'),
('Project: Funk Da World',1994,NULL,'Craig Mack'),
('Gincho Wataridori',1972,NULL,'Meiko Kaji'),
('Decade in the Sun: Best of Stereophonics',2008,NULL,'Stereophonics'),
('Wreckage',2003,NULL,'Overseer'),
('Business is Business',1996,NULL,'PMD'),
('The Storm',2017,NULL,'ZZ Ward'),
('Cheers',2003,NULL,'Obie Trice'),
('It''s All Good',1999,NULL,'MC Breed'),
('Sticks',2009,NULL,'Chris Joss'),
('Certified',2005,NULL,'David Banner'),
('Bonus Levels',2019,NULL,'Dibia$e'),
('Erotica',1992,NULL,'Madonna'),
('Greatest Hits',2002,NULL,'Will Smith'),
('Мама, Я Танцую (Single)',2018,NULL,'#2Маши'),
('Nothing Was the Same',2013,NULL,'Drake'),
('Планета 46',2006,NULL,'Смоки Мо'),
('Euphoria - Single',2012,NULL,'Loreen'),
('Paradise',1979,NULL,'Grover Washington, Jr.'),
('Seeekret',1985,NULL,'Kleeer'),
('Ролевая модель',2017,NULL,'Карандаш'),
('Joyful',2006,NULL,'Ayo'),
('Listen Without Prejudice Vol. 1',1990,NULL,'George Michael'),
('Ritual in Repeat',2014,NULL,'Tennis'),
('Прости меня моя любовь',2000,NULL,'Земфира'),
('Super 8',2018,NULL,'Synapson'),
('Monumental: Chapter I - EP',2017,true,'VARIOUS_ARTISTS'),
('Broadway & 52nd',1997,NULL,'Us3'),
('Modal Soul',2005,NULL,'Nujabes'),
('This Is Us, Season 3',2018,NULL,'This Is Us'),
('What''s Your Pleasure?',2020,NULL,'Jessie Ware'),
('Night Moves',1976,NULL,'Bob Seger & The Silver Bullet Band'),
('At Last!',1960,NULL,'Etta James'),
('Имя 505 - Single',2015,true,'VARIOUS_ARTISTS'),
('Oops!...I Did it Again',2000,NULL,'Britney Spears'),
('Fantastic Voyage: the Greatest Hits',2001,NULL,'Coolio'),
('Sax-A-Go-Go',1993,NULL,'Candy Dulfer'),
('Zapp',1980,NULL,'Zapp'),
('Trouble in Paradise',2014,true,'VARIOUS_ARTISTS'),
('Open Your Eyes',2002,NULL,'Goldfinger'),
('Bat Out of Hell',1977,NULL,'Meat Loaf'),
('All This Love',1982,NULL,'DeBarge'),
('Hard or Smooth',1992,NULL,'Wreckx-N-Effect'),
('This Is Us, Season 3',2019,NULL,'This Is Us'),
('How Do You Do',2011,NULL,'Mayer Hawthorne'),
('8th Wonder',1981,NULL,'The Sugarhill Gang'),
('U218 Singles',2016,true,'VARIOUS_ARTISTS'),
('Follow the Leader',1988,NULL,'Eric B. & Rakim'),
('Relapse',2009,NULL,'Eminem'),
('LP1',2011,NULL,'Joss Stone'),
('Black Ice',2008,NULL,'AC/DC'),
('Once Again',2006,NULL,'John Legend'),
('Beni Durdursan Mi',2013,NULL,'Gulsen'),
('...And Justice for All',1988,NULL,'Metallica'),
('Invincible',2001,NULL,'Michael Jackson'),
('Tin Can Trust',1988,NULL,'Los Lobos'),
('Epoch',2016,NULL,'Tycho'),
('A Little Deeper',2002,NULL,'Ms. Dynamite'),
('Die Laughing',1996,NULL,'Hyenas in the Desert'),
('Пора домой - Single',2016,true,'VARIOUS_ARTISTS'),
('Ibiza - Single',2018,NULL,'Филипп Киркоров & Николай Басков'),
('False Idols',2013,NULL,'Tricky'),
('War Zone',1999,NULL,'Black Moon'),
('Rage Against The Machine',1992,NULL,'Rage Against The Machine'),
('Here, My Dear',1978,NULL,'Marvin Gaye'),
('Only When We''re Naked',2017,NULL,'Zak Abel'),
('Where Does This Door Go',2013,true,'VARIOUS_ARTISTS'),
('All the King''s Horses',1972,NULL,'Grover Washington, Jr.'),
('Songs in the Key of Life',1976,NULL,'Stevie Wonder'),
('Featuring... Ice Cube',1997,NULL,'Ice Cube'),
('The Wrong Kind of War',2016,NULL,'Imany'),
('Seventeen Moments of Spring Soundtrack',2018,NULL,'Mikael Tariverdiev'),
('Take Me to Your Leader',2003,NULL,'King Geedorah'),
('The Number of the Beast',1982,NULL,'Iron Maiden'),
('Half Thang',1996,NULL,'Richie Rich'),
('On the Line',2019,NULL,'Jenny Lewis'),
('Blue Hawaii',1961,NULL,'Elvis Presley'),
('Far from Any Road (Main Title Theme from "True Detective") - Single',2014,true,'VARIOUS_ARTISTS'),
('Просвистела',1999,NULL,'ДДТ'),
('Later That Same Year',1970,NULL,'Matthews'' Southern Comfort'),
('Out of Ashes',2009,NULL,'Dead By Sunrise'),
('Safe + Sound',1995,NULL,'DJ Quik'),
('Organ Works (BWV 565, BWV 526, BWV 532, BWV 542)',1964,NULL,'Johann Sebastian Bach'),
('Forever Hustlin''',1995,NULL,'Ray Luv'),
('Like Water for Chocolate',2000,NULL,'Common'),
('Cry',2019,NULL,'Cigarettes After Sex'),
('The Woman In Me',1995,NULL,'Shania Twain'),
('Sing When You''re Winning',2000,NULL,'Robbie Williams'),
('Беспечный Ангел',2004,true,'VARIOUS_ARTISTS'),
('Я забираю твою подругу - Single',2020,NULL,'#2Маши'),
('Done with Mirrors',1985,NULL,'Aerosmith'),
('Вечерний Челябинск',2010,NULL,'Триагрутрика'),
('King of the Decks',2008,NULL,'DJ Revolution'),
('Бумер Soundtrack',2003,true,'VARIOUS_ARTISTS'),
('Demonstration',2013,NULL,'Tinie Tempah'),
('Be There EP',1999,NULL,'UNKLE'),
('Greatest Hits II',1991,NULL,'Queen'),
('Mountain of Memory',2020,NULL,'Emancipator'),
('Monkey Business',2005,NULL,'Black Eyed Peas'),
('SOULidified',2006,NULL,'Hil St. Soul'),
('Sweet Love - Single',2019,NULL,'Kiesza'),
('Мяу кисс ми',2001,true,'VARIOUS_ARTISTS'),
('No Angel',2000,NULL,'Dido'),
('Tuxedo II',2017,NULL,'Tuxedo'),
('Royal',2020,NULL,'Ayo'),
('Do You Want More?!!!??!',1994,NULL,'The Roots'),
('Pieces of a Man',1993,NULL,'Gil Scott-Heron'),
('Free',2009,NULL,'Lisa Shaw'),
('Решено - Single',2015,NULL,'Каста'),
('My Field Trip to Planet 9',1993,NULL,'Justin Warfield'),
('Total Eclipse',2003,NULL,'Black Moon'),
('Live in Montreux',1980,NULL,'Marvin Gaye'),
('Кукушка - Single',2015,true,'VARIOUS_ARTISTS'),
('Agents of Fortune',1976,NULL,'Blue Öyster Cult'),
('Skye | Ross',2016,NULL,'Skye & Ross'),
('You''ve Come a Long Way, Baby',1998,NULL,'Fatboy Slim'),
('No Geography',2019,NULL,'The Chemical Brothers'),
('Catalogue',2006,NULL,'Moloko'),
('The Clones of Dr. Funkenstein',1976,NULL,'Parliament'),
('Lemonade',2016,true,'VARIOUS_ARTISTS'),
('Migration',2017,NULL,'Bonobo'),
('Be Mine - Single',2016,NULL,'Ofenbach'),
('The Razors Edge',1990,NULL,'AC/DC'),
('No Mythologies to Follow',2014,NULL,'MØ'),
('The Eminem Show',2002,NULL,'Eminem'),
('Directors of Photography',2014,NULL,'Dilated Peoples'),
('The Sound of Revenge',2005,NULL,'Chamillionaire'),
('Nothing Remain the Same',2002,NULL,'Pain'),
('Stiff Upper Lip',2000,NULL,'AC/DC'),
('Maxinquaye',1995,NULL,'Tricky'),
('Fancy Footwork',2007,NULL,'Chromeo'),
('Chant Down Babylon',1999,NULL,'Bob Marley & The Wailers'),
('Dirt',1992,true,'VARIOUS_ARTISTS'),
('To Be Free',2008,NULL,'Nina Simone'),
('Bass Cannon - Single',2011,true,'VARIOUS_ARTISTS'),
('Rockabye (feat. Sean Paul & Anne-Marie) - Single',2016,NULL,'Clean Bandit'),
('Papillon',2019,NULL,'Lara Fabian'),
('Easy Street (feat. Jim Bianco & Petra Haden) - Single',2016,NULL,'The Collapsable Hearts Club'),
('Born to Die',2012,NULL,'Lana Del Rey'),
('Dive Deep',2008,NULL,'Morcheeba'),
('Everythang''s Corrupt',2018,NULL,'Ice Cube'),
('Tragic Kingdom',1995,NULL,'No Doubt'),
('Stories',2015,NULL,'Avicii'),
('The Fall',2010,NULL,'Gorillaz'),
('Как в последний раз (Maxi-Single)',2016,NULL,'Порнофильмы'),
('Angels with Dirty Faces',2002,NULL,'Sugababes'),
('Wounded Rhymes',2012,NULL,'Lykke Li'),
('The Antidote',2005,NULL,'Morcheeba'),
('The College Dropout',2004,NULL,'Kanye West'),
('St. Anger',2003,NULL,'Metallica'),
('Toto IV',1982,NULL,'Toto'),
('GRAND Collection vol.2',2011,NULL,'Сергей Трофимов'),
('Т.Г.К.липсис',2011,NULL,'Триагрутрика'),
('Jagatud Saladus - Single',2018,NULL,'Elina Born & Jüri Pootsmann'),
('Life of a Kid in the Ghetto',1991,NULL,'Ed O.G. & Da Bulldogs'),
('Pre-Millennium Tension',1996,NULL,'Tricky'),
('Insomniac',1995,NULL,'Green Day'),
('Hybrid',2007,NULL,'Elsiane'),
('Трудное Детство',1995,NULL,'Владимир Маркин'),
('Celebrate (Single)',2011,NULL,'Common'),
('Against The Wind',1980,NULL,'Bob Seger & The Silver Bullet Band'),
('Hard Core',1996,NULL,'Lil'' Kim'),
('Земфира',1999,NULL,'Земфира'),
('Formidable - Single',2013,true,'VARIOUS_ARTISTS'),
('Hand of Blood / 4 Words - Single',2005,NULL,'Bullet for My Valentine'),
('Groovejet (If This Ain''t Love) (CDM)',2000,NULL,'Spiller'),
('Zapp III',1983,NULL,'Zapp'),
('Avalanche',2013,NULL,'Quadron'),
('Четырнадцать недель тишины',2002,NULL,'Земфира'),
('Load',1996,NULL,'Metallica'),
('Bad Boys Soundtrack',1995,true,'VARIOUS_ARTISTS'),
('Paul''s Boutique',1989,NULL,'Beastie Boys'),
('Tough Love',2014,NULL,'Jessie Ware'),
('Le Meilleur De Joe Dassin',1995,NULL,'Joe Dassin'),
('Романсы',2012,true,'VARIOUS_ARTISTS'),
('UNO - Single',2020,NULL,'Little Big'),
('The Emancipation of Mimi',2005,NULL,'Mariah Carey'),
('Diary of a Mad Band',1993,NULL,'Jodeci'),
('Dirty Vegas',2002,NULL,'Dirty Vegas'),
('Maysa',1995,NULL,'Maysa'),
('The Essential',2007,true,'VARIOUS_ARTISTS'),
('Strictly 4 My N.I.G.G.A.Z...',1993,NULL,'2Pac'),
('Fearless',2008,NULL,'Jazmine Sullivan'),
('From Sarah with Love (CDM)',2001,NULL,'Sarah Connor'),
('Third',2008,NULL,'Portishead'),
('Conspiracy of One',2000,NULL,'The Offspring'),
('Time is Slipping Away',1979,NULL,'Dexter Wansel'),
('Пущенная Стрела (Избранное 1982-2012)',2013,true,'VARIOUS_ARTISTS'),
('Music & Me',2001,NULL,'Nate Dogg'),
('You Been Played',1993,NULL,'Smooth'),
('Big Girl',1995,NULL,'Candy Dulfer'),
('The Greatest Story Ever Told',2008,NULL,'David Banner'),
('Broken Bells',2010,NULL,'Broken Bells'),
('Draw the Line',1977,NULL,'Aerosmith'),
('Franz Ferdinand',2004,NULL,'Franz Ferdinand'),
('Ultimate Victory',2007,NULL,'Chamillionaire'),
('The Moan EP',2004,NULL,'The Black Keys'),
('Soundtrack - EP',2015,true,'VARIOUS_ARTISTS'),
('Black Water',2018,true,'VARIOUS_ARTISTS'),
('Кольщик - Single',2017,true,'VARIOUS_ARTISTS'),
('Incesticide',1992,NULL,'Nirvana'),
('Lil Red Riding Hood',2009,NULL,'Jacki-O'),
('Endtroducing...',1996,NULL,'DJ Shadow'),
('Let Me Clear My Throat (CDM)',1997,NULL,'DJ Kool'),
('Domino',1993,NULL,'Domino'),
('Thriller',1982,NULL,'Michael Jackson'),
('Voulez-Vous',1979,NULL,'ABBA'),
('Anthology',1986,NULL,'Diana Ross'),
('I Never Learn',2014,NULL,'Lykke Li'),
('The Point of No Return',2014,NULL,'Hugo Kant'),
('Duophonic',1992,NULL,'Charles & Eddie'),
('Mo Bounce - Single',2017,NULL,'Iggy Azalea'),
('неболей - Single',2020,NULL,'Баста & Zivert'),
('Intimate Connection',1984,NULL,'Kleeer'),
('MTV Unplugged No. 2.0',2002,NULL,'Lauryn Hill'),
('Nixon Pryor Roundtree',2002,NULL,'Richie Rich'),
('Paid in Full',1987,NULL,'Eric B. & Rakim'),
('Brothers',2010,NULL,'The Black Keys'),
('Night in the Ruts',1979,NULL,'Aerosmith'),
('Born to Do It',2001,NULL,'Craig David'),
('GRAND Collection vol.1',2007,NULL,'Стас Михайлов'),
('Strictly Garage',1999,true,'VARIOUS_ARTISTS'),
('Carnival of Rust',2006,NULL,'Poets of the Fall'),
('Boyz N Da Hood',2005,NULL,'Boyz N Da Hood'),
('Loud',2010,NULL,'Rihanna'),
('Something New: Motown Lost & Found',2012,true,'VARIOUS_ARTISTS'),
('Aktapuss',1999,NULL,'Akinyele'),
('Lucinda Williams',1988,NULL,'Lucinda Williams'),
('Heavy Load',1994,NULL,'Jamaica Papa Curvin'),
('Supreme Clientele',2000,NULL,'Ghostface Killah'),
('Real Brothas',1995,NULL,'B.G. Knocc Out & Dresta'),
('I Am...Sasha Fierce',2009,true,'VARIOUS_ARTISTS'),
('Musique Vol. 1 1993-2005',2006,true,'VARIOUS_ARTISTS'),
('Reachin'' (A New Refutation of Time and Space)',1993,NULL,'Digable Planets'),
('The Predator',1992,NULL,'Ice Cube'),
('London Soundtrack',2005,true,'VARIOUS_ARTISTS'),
('Bullets Through the Speaker',2007,NULL,'Hochii'),
('Margie',1975,NULL,'Margie Joseph'),
('New Amerykah: Part One (4th World War)',2008,NULL,'Erykah Badu'),
('Wishful Thinking',2002,NULL,'Edo.G'),
('Mezzanine',1998,NULL,'Massive Attack'),
('R.O.O.T.S.',2009,NULL,'Flo Rida'),
('Gap Band IV',1982,NULL,'The Gap Band'),
('Zapp II',1982,NULL,'Zapp'),
('The Infamous',1995,NULL,'Mobb Deep'),
('Lost on You (Swanky Tunes & Going Deeper Remix) - Single',2016,NULL,'LP'),
('Dig This!',1972,NULL,'Bobbi Humphrey'),
('He Touched Me',1972,NULL,'Elvis Presley'),
('Bondage Fairies',2012,NULL,'Bondage Fairies'),
('Chromatica',2020,NULL,'Lady Gaga'),
('Lost on You',2016,true,'VARIOUS_ARTISTS'),
('Dat Whoopty Woop',2001,NULL,'Soopafly'),
('Golden Tunes',2013,NULL,'8-BITchin’tendo'),
('Greatest Hits',2007,NULL,'Spice Girls'),
('Greatest Hits',2004,NULL,'Robbie Williams'),
('Greatest Hits',2005,NULL,'*NSYNC'),
('Greatest Hits',2010,NULL,'Lara Fabian');