INSERT INTO library.artists (name) VALUES 
('Wolf Myer Orchestra'),
('Jaded Incorporated'),
('VARIOUS_ARTISTS'),
('James Brown'),
('Pharoahe Monch'),
('Tony Martin'),
('Aphrodisia'),
('Gil Scott-Heron & Brian Jackson'),
('Maurice Jarre'),
('Event'),
('702'),
('Keith Martin'),
('Nightwish'),
('J-Flexx'),
('Kanye West'),
('David Guetta & Sia'),
('Rappin'' 4-Tay'),
('Earl Washington All Stars'),
('Walkin'' Large'),
('MARUV & Boosin'),
('88-Keys'),
('Lee & The Leopards'),
('Edo.G'),
('Los Bravos'),
('Dru Down'),
('Bergendy'),
('Main Source'),
('The Spinners'),
('The Outlawz & Daz Dillinger'),
('Emma Stone'),
('Beyoncé'),
('Карнеги Дейл'),
('Pat Benatar'),
('Ed Sheeran'),
('Lil'' Scrappy'),
('The Delfonics'),
('The Velvelettes'),
('Justin Hurwitz'),
('Tim Roth & Kurt Russell'),
('Eminem'),
('Chicken Lips'),
('Marvin Gaye & Mary Wells'),
('Margie Joseph'),
('Audioslave'),
('John Travolta'),
('Tha Gang'),
('Dave Porter'),
('Madcon'),
('Mack 10'),
('Ms. Dynamite'),
('Larry Lurex'),
('Erykah Badu'),
('Kenny G'),
('Isaac Hayes'),
('Ogun'),
('The Majestics'),
('Run-D.M.C.'),
('Aardvarck'),
('Yerzmyey'),
('Earl Van Dyke'),
('Время и Стекло'),
('The Box Tops'),
('Maysa'),
('Club des Belugas'),
('Charlie Feathers'),
('The Amalgamation of Soundz'),
('Johann Sebastian Bach'),
('6 Feet'),
('Johnny Mathis'),
('Queen Mother Rage'),
('Chad & Jeremy'),
('Spice 1'),
('Eddie Vedder'),
('Billy Joel'),
('Bobby Helms'),
('Coolio'),
('Funkmaster Flex'),
('Various Artists'),
('Noize MC'),
('RL Grime'),
('Soulja Boy'),
('The Weavers'),
('Showbiz'),
('Lady Gaga & Bradley Cooper'),
('S Dot'),
('Papa Roach'),
('Stevie Wonder'),
('Blind Scuba Divers'),
('Nina Nesbitt'),
('Диоды'),
('DJ Kool'),
('Avicii'),
('Geto Boys'),
('Gustav Holst'),
('The RZA'),
('Juster'),
('Justice vs. Simian'),
('Pink'),
('Lunatic Calm'),
('The Rasmus'),
('A'),
('The Out Crowd'),
('Anthony Hamilton'),
('Parov Stelar Trio'),
('Clicks & Whistles'),
('Filatov & Karas'),
('Herman Griffin'),
('Ramin Djawadi'),
('Majbour'),
('Luminox'),
('Guru'),
('Arcangelo Corelli'),
('Dinosaur Jr. & Del Tha Funkee Homosapien'),
('Melanie Fiona'),
('Dr. Dre'),
('DoMaJe'),
('Burak Yeter'),
('Q-Tip'),
('Diplo'),
('Harold E. Weed / Dana Classic Fragrances'),
('Света Колiбаба'),
('Jade Bird'),
('Eve'),
('Fugees'),
('Patrice Holloway'),
('t.A.T.u.'),
('Justin Warfield'),
('Markus Enochson'),
('The Firm'),
('Miles Davis'),
('Illegal'),
('Okura'),
('Ignaz Holzbauer'),
('Chris Joss'),
('Sarah Connor'),
('Marvin Gaye & Kim Weston'),
('Lafayette Gilchrist'),
('Ace of Base'),
('The Doors'),
('Ying Yang Twins'),
('Meiko Kaji'),
('My Morning Jacket'),
('Ленин'),
('Propellerheads'),
('Alice in Chains'),
('London Funk Allstars'),
('Spice Girls'),
('Bloodstone'),
('Kool & The Gang'),
('Blakroc'),
('Johann Pachelbel'),
('John Legend'),
('IOWA'),
('Burl Ives'),
('Владимир Высоцкий'),
('N.W.A'),
('Brand Nubian'),
('Command com'),
('J Flex'),
('Johnny Griffith Trio'),
('Keni Burke'),
('Parov Stelar'),
('Chuck Berry'),
('Hpntk'),
('Stine J'),
('Dr. Dre & Ice Cube'),
('Montserrat Caballé'),
('Nine Inch Nails'),
('Element Eighty'),
('Kid Sundance'),
('Nil Karaibrahimgil'),
('Ingushit TGK'),
('Diana Ross'),
('Northbank'),
('Pat Boone'),
('Mel Tormé'),
('Chain Reaction'),
('The Bob Seger System'),
('Charlie Parker'),
('E-40'),
('Cold War Kids'),
('Ляпис Трубецкой'),
('Bill Withers'),
('Kenny Loggins'),
('Two Towers'),
('Thefender'),
('Stromae'),
('Ennio Morricone'),
('blink-182'),
('The Charters'),
('Chamillionaire'),
('UGK'),
('Afrika Bambaataa & The Soulsonic Force'),
('Kiesza'),
('Therapy? & Fatal'),
('Craig David'),
('Jahmal TGK'),
('Mitch Miller'),
('Alanis Morissette'),
('Iggy Azalea'),
('Dilated Peoples'),
('Tuxedo'),
('Evelyn "Champagne" King'),
('Kleeer'),
('Mario Lanza'),
('Oliver Cheatham'),
('Cigarettes After Sex'),
('Lisa Stansfield'),
('Dee Clark'),
('Nico Krop'),
('Helmet & House of Pain'),
('Tommy Good'),
('Étienne de Crécy'),
('Slick Rick'),
('Norther'),
('Skye & Ross'),
('The Platters'),
('Eddie Holland'),
('Валерия'),
('Haruomi Hosono'),
('The Miracles'),
('John Lee Hooker'),
('Marky Mark & The Funky Bunch'),
('Los Cuates De Sinaloa'),
('Robert Corff'),
('Pete Hartfield'),
('Фёдор Шаляпин'),
('Scarlett Johansson'),
('Jackie'),
('Jamaica Papa Curvin'),
('UNKLE'),
('The Conscious Daughters'),
('Bob Seger'),
('The S.O.U.L. S.Y.S.T.E.M.'),
('Wojciech Kilar'),
('Lenny Kravitz'),
('Young Soldierz'),
('Samuel L. Jackson, Walton Goggins & Bruce Dern'),
('Lamont Dozier'),
('Tycho'),
('Richie Rich & The Mekanix'),
('Jethro Tull'),
('The Discoettes'),
('Singin'' Sammy Ward'),
('Zamfir'),
('Big Wild'),
('Huey Lewis & the News'),
('The Pussycat Dolls'),
('Robert De Niro & Samuel L. Jackson'),
('Earth, Wind & Fire'),
('Ant Banks'),
('Blue Öyster Cult'),
('Интарс Бусулис'),
('The Andrews Sisters & Bing Crosby'),
('Justice'),
('Bomfunk MC''s'),
('Dido'),
('Daniel Pemberton'),
('Dan Curtin'),
('Busta Rhymes'),
('Gil Scott-Heron'),
('Society'),
('Massappeals'),
('Lee Alan'),
('The Roots'),
('The Grass Roots'),
('Doug E. Fresh & The Get Fresh Crew'),
('Backstreet Boys'),
('The Honey Drippers'),
('Natalia Oreiro'),
('Anna Naklab'),
('KRS-One'),
('Jason Weaver, Rowan Atkinson & Laura Williams'),
('LL Cool J'),
('Nick & The Jaguars'),
('The 5.6.7.8''s'),
('Barrett Strong'),
('Gino Parks'),
('8-BITchin’tendo'),
('Santana'),
('Ella Fitzgerald & Bing Crosby'),
('Frankie Laine'),
('Martina Topley-Bird'),
('Rae & Christian'),
('Herman Griffin & Band'),
('The Perceptionists'),
('Hilltop Hoods'),
('Casual'),
('The Golden Harmoneers'),
('Marvin Gaye & Diana Ross'),
('Teenage Fanclub & De La Soul'),
('Marv Johnson'),
('Roy Head & The Traits'),
('Iron Maiden'),
('Courtney Pine'),
('Frank Sinatra'),
('The Hornets'),
('Zivert'),
('Fort Minor'),
('Freddie Mercury & Montserrat Caballé'),
('Britney Spears'),
('Bingo Players'),
('Lloyd Charmers'),
('DJ Snake & Lil Jon'),
('Ashanti'),
('F-Mob'),
('Instrumental'),
('Basement Kru'),
('Coty Inc.'),
('Red Hot Chili Peppers'),
('Lauryn Hill'),
('Badfinger'),
('Calexico'),
('Little Big'),
('International Pony'),
('Leroy Hanghofer'),
('Гости из будущего'),
('Punk Barbarians'),
('Freddie Gorman'),
('J. Flex'),
('Johann Strauss I'),
('Jewell'),
('Etta James'),
('Bertie Higgins'),
('Hozier'),
('The Chemical Brothers'),
('Matthews'' Southern Comfort'),
('Joanne & The Triangles'),
('Joss Stone'),
('Сектор Газа'),
('Jim Croce'),
('Каста'),
('Stephanie Cooke'),
('Metallica'),
('Choker Campbell''s Big Band'),
('Holland & Dozier'),
('Young MC'),
('Ricky Martin'),
('The Chocolate Watchband'),
('Channel Live'),
('Iyeoka'),
('MATRANG'),
('Elton John'),
('Method Man'),
('Cast'),
('The Smiths'),
('Angel Haze'),
('Oasis'),
('The Perishers'),
('Kurt Russell & Michael Madsen'),
('Luigi Boccherini'),
('Just Jack'),
('Carolyn Crawford'),
('Heart'),
('T-Love'),
('Billie Holiday'),
('The Staple Singers'),
('Stereophonics'),
('Dirty Elegance'),
('Perry Como'),
('Звери'),
('Стас Михайлов'),
('Jerry Goldsmith'),
('Charlotte Qvale'),
('Jessie Ware'),
('Theory of a Deadman'),
('M.O.P.'),
('Modjo'),
('Frank Sinatra & Gordon Jenkins'),
('Noora Noor'),
('Джером Джером Клапка'),
('Judy Garland & Victor Popular Young'),
('The J. Geils Band'),
('Guano Apes'),
('Snoop жаба жаб'),
('Special Ed'),
('Brian Bennett'),
('The Centurians'),
('The Notorious B.I.G.'),
('Moby'),
('MARUV'),
('Vanilla Fudge'),
('Monk Higgins'),
('Emma Bunton'),
('Grav'),
('Ol'' Dirty Bastard'),
('Lil Jon, Offset & 2 Chainz'),
('Gass'),
('Biohazard & ONYX'),
('Bob Kayli'),
('Oakenfold'),
('The Avener'),
('George Michael'),
('The Avener & Mazzy Star'),
('Sammy Turner'),
('Kwabs'),
('La La Land Cast'),
('Maceo'),
('Ill Al Skratch'),
('Fleetwood Mac'),
('Ghostface Killah'),
('B.G. Knocc Out & Dresta'),
('*NSYNC'),
('Linda Griner'),
('Charli XCX'),
('Tinashe'),
('Mitch Ryder & The Detroit Wheels'),
('James Last'),
('Rah Digga'),
('Diablo'),
('Steven Tyler'),
('The Vells'),
('The Everly Brothers'),
('Nino Rota'),
('Buffy Sainte-Marie'),
('Black Milk'),
('Curtis Stigers'),
('Talib Kweli & Madlib'),
('Demis Roussos'),
('Ll Cool J'),
('The Equadors'),
('Soulful Illusion'),
('This Is Us'),
('Jon B.'),
('SEREBRO'),
('Raw Deal'),
('Chuck-A-Lucks'),
('The Temptations'),
('ZZ Ward'),
('PMD'),
('Eddy Arnold'),
('Sum 41'),
('Jaylib'),
('Maggie Rogers'),
('Big Noyd'),
('The Avener & Phoebe Killdeer'),
('Norah Jones'),
('Luigi Tenco'),
('Quincy Jones'),
('Saukrates'),
('Young Buck'),
('John Powell'),
('Peppino Gagliardi'),
('Green Day'),
('Elina Born'),
('Caesars Palace'),
('Bernhoft'),
('The Isley Brothers'),
('I Profumi di Capri'),
('Gang Starr'),
('Steve Aoki, Diplo & Deorro'),
('Joel Sebastion'),
('Edwin Starr'),
('XXTRAKT'),
('Джером Клапка Джером'),
('Yen Sung'),
('Montell Jordan'),
('Lil Jon'),
('Future'),
('Мумий Тролль'),
('Parliament'),
('Harry Belafonte'),
('Butti 49'),
('Foxy Brown'),
('Doug E. Fresh'),
('Nelly Furtado'),
('Migos, Nicki Minaj & Cardi B'),
('Lucinda Williams'),
('Al Martino'),
('Louis St. Louis'),
('Dusty Springfield'),
('TLC'),
('Lisa Shaw'),
('Fatboy Slim'),
('Lykke Li'),
('Tha Dogg Pound'),
('Netta'),
('Richard Wylie & His Band'),
('Bernard Hermann'),
('Tracey Lee'),
('Chromeo'),
('Sonique'),
('Harold Melvin & the Blue Notes'),
('Hank Shocklee'),
('Mariah Carey'),
('Roberta Flack'),
('3 Doors Down'),
('Major Lazer'),
('Marshmello & Anne-Marie'),
('Young Money'),
('Giuseppe Verdi'),
('Yvette Michele'),
('Randy Crawford'),
('Air Supply'),
('Army of the Pharaohs'),
('Computerjockeys'),
('Yma Sumac'),
('Jimmy Ruffin'),
('Eugene Remus'),
('Chrisette Michele'),
('Steve Winwood'),
('Flo Rida'),
('Charles Gounod'),
('Scott Garcia'),
('Antonín Dvořák'),
('Richie Rich'),
('The Headliners'),
('George Bohannon Quartet'),
('Da Lench Mob'),
('Redman & Method Man'),
('Connie Francis'),
('Bill & Ron'),
('Johann Strauss II'),
('Shermanology & GRX'),
('Stanley Myers'),
('Jean Grae'),
('The Govenor & House Reps'),
('Солженицын Александр'),
('Little People'),
('Public Enemy'),
('Kelis'),
('Kacey Musgraves'),
('Nicholas Britell & Justin Hurwitz'),
('Mac Mall'),
('Hugo Kant'),
('Tiesto'),
('Galt MacDermot'),
('Pam Grier'),
('Call O'' Da Wild'),
('The Chainsmokers'),
('A Tribe Called Quest'),
('Gerd'),
('Eric Burdon & The Animals'),
('Vampire''s Sound Incorporation'),
('Roy Orbison'),
('Caravan Palace'),
('Capricorn'),
('Shy''m'),
('Puff Daddy'),
('New Hope'),
('David Sun'),
('Twaughthammer'),
('Phil Collins'),
('Hans Zimmer'),
('Duck Sauce'),
('Marselle'),
('Gesaffelstein'),
('Edward Elgar'),
('Chris Isaak'),
('Louis St. Louis & Cindy Bullens'),
('ABBA'),
('Lara Fabian'),
('Chingon'),
('Кино'),
('The D.O.C.'),
('Ван Дайн Стивен'),
('Gioachino Rossini'),
('#2Маши'),
('Marina'),
('Владимир Маркин'),
('Tomoyasu Hotei'),
('S. Dot'),
('Living Colour & Run-D.M.C.'),
('Labrenda Ben'),
('Jay-Z'),
('David Carradine, Julie Dreyfus & Uma Thurman'),
('The Walkmen'),
('Deep Purple'),
('Daz Dillinger'),
('Simon & Garfunkel'),
('Remo Giazotto'),
('Jenny Lewis'),
('2nd II None'),
('Bridget Fonda, Robert De Niro & Samuel L. Jackson'),
('Replacement Killers'),
('Claude Debussy'),
('Erik Satie'),
('Nathan Lane, Ernie Sabella, Jason Weaver & Joseph Williams'),
('Goldfinger'),
('Meat Beat Manifesto'),
('P.O.D.'),
('DJ Technics'),
('Pete Yorn & Scarlett Johansson'),
('Kim Weston'),
('Johannes Brahms'),
('Jay Rock'),
('Lords of the Underground'),
('Whitney Houston'),
('Ленинград'),
('Stargate'),
('Us3'),
('Megadeth'),
('Sammy Ward'),
('Nouvelle Vague'),
('Кинг Стивен'),
('The In Crowd'),
('Danny Boy'),
('Елена Ваенга'),
('Billie Eilish'),
('Shivaree'),
('Dean Martin'),
('LOBODA & PHARAOH'),
('The Swinging Tigers'),
('8-Bitchin''tendo'),
('Def Squad'),
('Henry Tozer'),
('Sha-Na-Na'),
('The Burnadettes'),
('Diana King'),
('Bob Seger & The Silver Bullet Band'),
('The Prodigy'),
('Broken Bells'),
('Masters at Work'),
('Roxette'),
('Don McKenzie'),
('Connie Van Dyke'),
('Artifacts'),
('Prophets of Rage'),
('Rag''n''Bone Man'),
('Loboda'),
('Janet Jackson'),
('Monie Love'),
('Steely Dan'),
('Bobby Breen'),
('Overseer'),
('Annibale e i Cantori Moderni'),
('Antonio Vivaldi'),
('The Delinquents'),
('The Glitch Mob'),
('Keith Murray & Redman'),
('Smooth'),
('MN8'),
('Hakan Lidbo'),
('Limp Bizkit'),
('Ariano'),
('Pixel Nya'),
('Bruno Mars'),
('Johnny Mathis & Percy Faith'),
('Spider Loc'),
('The Contours'),
('Cindy Bullens'),
('Daniel Klein'),
('Don Straud'),
('Mickey Woods'),
('Tyree Colion'),
('James Russo'),
('Depeche Mode'),
('The Beatles'),
('Linkin Park'),
('Morcheeba'),
('Nuttin'' Nyce'),
('8-Bitchin’tendo'),
('EPMD'),
('Rob Zombie'),
('Michael Jackson'),
('Troy Bonnes'),
('Method Man & Redman'),
('Диман'),
('Makaveli'),
('Toni Braxton'),
('Ricky Nelson'),
('Carly Rae Jepsen'),
('Bedřich Smetana'),
('Mable John'),
('En Vogue'),
('Vanessa Amorosi'),
('Methods of Mayhem'),
('Charles Aznavour'),
('The Crystal Mansion'),
('DJ Deckstream'),
('Carmine Coppola'),
('The Collapsable Hearts Club'),
('Travis Barker'),
('Captain & Tennille'),
('Bro Safari'),
('Bobbi Humphrey'),
('Boston'),
('Sting'),
('The Andrews Sisters'),
('Sofa'),
('Judy Garland'),
('The Moonglows'),
('Saundra Mallet & The Vandellas'),
('The Brand New Heavies'),
('Bruce Channel'),
('Natan'),
('Jennifer Hudson'),
('Ludacris'),
('Stan Kenton'),
('Ludwig van Beethoven'),
('Artik & Asti'),
('Akinyele'),
('Cody ChesnuTT'),
('Moonstarr'),
('The Twistin'' Kings'),
('Lloyd Banks'),
('Låpsley'),
('Debbie Dean'),
('Mopse'),
('Aphex Twin'),
('Dave Hamilton'),
('Killer Mike'),
('Wreckx-N-Effect'),
('Francesca Belmonte'),
('Muse'),
('69 Boyz'),
('Little Iva & Her Band'),
('40 Thevz'),
('The Beverly Sisters'),
('The Cameos'),
('Анна Герман'),
('Joy Division'),
('Pearl Jam'),
('Дюма Александр'),
('Black Pistol Fire'),
('Ed O.G. & Da Bulldogs'),
('Little Stevie Wonder'),
('Quasimoto'),
('Outkast'),
('U-God'),
('Calypso King & The Soul Investigators'),
('Akinyele & Sadat X'),
('Deetron'),
('Rod Lee'),
('Jackers'),
('B.G.O.T.I.'),
('Frankie Cutlass'),
('Soft Cell'),
('Atreyu'),
('Zara Larsson'),
('Daniel J. White'),
('Afrika Bambaataa'),
('Johann Christian Cannabich'),
('Ice Cube'),
('Coldplay'),
('Mike Shinoda'),
('Hoobastank'),
('Lou Doillon'),
('The Crystal Method'),
('Bloodhound Gang'),
('Tobias Jesso Jr.'),
('MC Lyte'),
('Nas'),
('Quadron'),
('Ella Fitzgerald'),
('Alvin ''Red'' Tyler'),
('Second Hand Band'),
('Society of Seven'),
('Crystal Castles'),
('The Valadiers'),
('Good Charlotte'),
('Shania Twain'),
('PSY'),
('Aura Dione'),
('Kenny G & Aaron Neville'),
('Spike Jones'),
('No Doubt'),
('Barrington Levy'),
('Huey Lewis & The News'),
('Amos Milburn'),
('Sofia Karlberg'),
('Luniz'),
('Ray Luv'),
('Junior Walker & The All Stars'),
('Ahmad'),
('Led Zeppelin'),
('Rosemary Clooney'),
('Я и друг мой грузовик'),
('Михаил Шуфутинский'),
('The Marvelettes'),
('Paradise'),
('Hidden Orchestra'),
('Paris'),
('Смысловые галлюцинации'),
('LP'),
('Martha Reeves & The Vandellas'),
('The Morrocco Muzik Makers'),
('Three 6 Mafia'),
('The Gap Band'),
('Madonna'),
('Sia'),
('Samuel Barber'),
('Кишими Ичиро; Каго Фумитаке'),
('Charli Baltimore'),
('Masta Ace'),
('Gabriel Fauré'),
('Bandini'),
('Mary Jane Girls'),
('Infected Mushroom'),
('Guilty Simpson'),
('Shop Boyz'),
('Joe Dassin'),
('Carole King'),
('ALEKSEEV'),
('Pyotr Ilyich Tchaikovsky'),
('Hande Yener'),
('Unloco'),
('Camille Saint-Saëns'),
('Spiller'),
('Sergei Rachmaninoff'),
('Макиавелли Никколо'),
('Meat Loaf'),
('Thievery Corporation'),
('R. Dean Taylor'),
('Soopafly'),
('Frankie Valli'),
('Timbaland'),
('LaBrenda Ben & The Beljeans'),
('Black Moon'),
('Petey Pablo'),
('David Carradine & Uma Thurman'),
('U2'),
('Breakbot'),
('Ryan Gosling'),
('David Banner'),
('Akon'),
('Felix Mendelssohn'),
('Cheryl Lynn'),
('The Statler Brothers'),
('Shaggy'),
('8-Bitchin’tendo & Pixel Nya'),
('Ayo'),
('Krec'),
('ВИА Гра'),
('Kaotic Style'),
('ОД Белый Рэп'),
('Carl Orff'),
('Georg Friedrich Händel'),
('Brother Lloyd''s All Stars'),
('Wiz Khalifa'),
('Scarface'),
('Groove Armada'),
('Samuel L. Jackson'),
('Сунь-Цзы'),
('David Whitfield'),
('Леонид Агутин & Анжелика Варум'),
('Doris Day'),
('Tinie Tempah'),
('David Batiste & The Gladiators'),
('Marvin Berry & the Starlighters'),
('Popcorn And The Mohawks'),
('Lindsey Buckingham'),
('Alana D'),
('Ария'),
('Zak Abel'),
('50 Cent'),
('Aerosmith'),
('Donald Byrd'),
('Maria McKee'),
('Biz Markie'),
('Mykill Miers'),
('Henry Lumpkin'),
('Uma Thurman'),
('Blue Foundation'),
('Белый Орел'),
('Nujabes'),
('Baauer'),
('The Velvettes'),
('Robbie Williams'),
('Rosie Gaines'),
('Dorsey Burnette'),
('Roland'),
('Sugababes'),
('Laura Vane & The Vipertones'),
('Lucien Belmond'),
('Temporary Soundmuseum'),
('The Hillfiguzes'),
('Rihanna'),
('Sky King'),
('Серёга'),
('Bradley Cooper'),
('Rasta T'),
('The Black Keys'),
('Deftones'),
('Eric Prydz'),
('Dat Nigga Daz'),
('Дискотека Авария'),
('The Revels'),
('Foals'),
('Teresa Brewer'),
('Steppenwolf'),
('Charles & Eddie'),
('Queen'),
('Rahzel'),
('Busy P'),
('8mm'),
('Hucci & Stooki Sound'),
('Emma Stone, Callie Hernandez, Sonoya Mizuno & Jessica Rothe'),
('Lil Jon & The East Side Boyz'),
('Bobby Womack'),
('Swell Session'),
('Brother Dege (aka Dege Legg)'),
('Perry Como & Mitchell Ayres'),
('The Brothers Johnson'),
('The Righteous Brothers'),
('Bullet for My Valentine'),
('Minnie Riperton'),
('Edgar Froese'),
('Common'),
('WC, CJ Mac, Daz Dillinger & Tray Dee'),
('Sammy Davis, Jr.'),
('2raumwohnung'),
('Eddy & Dus'),
('Порнофильмы'),
('Драйзер Теодор'),
('АК-47'),
('Zaz'),
('Action Bronson'),
('David Hess'),
('Jamal'),
('Thug Life'),
('James Brown & 2Pac'),
('Team Sleep'),
('Otis Redding'),
('Gramatik'),
('Gary Clark Jr.'),
('Beastie Boys'),
('Yellowman'),
('Da Brat'),
('Stevie Wonder & Clarence Paul'),
('Incognito'),
('Luther Vandross'),
('Ministry'),
('Kabuki'),
('Mudhoney & Sir Mix-A-Lot'),
('Kam'),
('Gent & Jawns'),
('Del Tha Funkee Homosapien'),
('Maxwell'),
('Juno Reactor'),
('Redman'),
('Jah Khalib'),
('Barbra Streisand'),
('Isaac Delusion'),
('Sonic Youth & Cypress Hill'),
('Supercommuter'),
('Trackheadz'),
('Nas & Damian Marley'),
('Katy B'),
('Parra for Cuva'),
('Johnny Cash'),
('L''One'),
('Wham!'),
('George Bizet'),
('Spanish Inquisition'),
('The Tornadoes'),
('Council Cargle'),
('Hucci'),
('The Heads of the Family'),
('ДДТ'),
('DANGERDOOM'),
('Leaf'),
('Леонид Фёдоров'),
('DJ Snake'),
('System of a Down'),
('Ini Kamoze'),
('Gheorghe Zamfir'),
('MØ'),
('Nancy Sinatra'),
('Jack Haney & Nikiter Armstrong'),
('Ennio Morricone & Walter Goggins'),
('J. Stalin'),
('Connie Price & The Keystones'),
('W.A.S.P.'),
('Sade'),
('Black Eyed Peas'),
('Greg Joy'),
('Кирпичи'),
('Urge Overkill'),
('Rammstein'),
('Des''Ree'),
('Quest Pistols Show & MONATIK'),
('Missy Elliott'),
('Zager & Evans'),
('Voodoo Glow Skulls'),
('Hattie Littles'),
('Kaleo'),
('Elliot Easton''s Tiki Gods'),
('Michel''le'),
('The Game'),
('Frankie Avalon'),
('David Campbell'),
('Klingande'),
('Lowell Fulson'),
('Yalin'),
('Loreen'),
('Fluke'),
('Jean Sibelius'),
('Gizelle Smith & The Mighty Mocambos'),
('MC Trouble'),
('Sabu Martinez'),
('Double F. & J. Dilla'),
('Ensiferum'),
('Tony Yayo'),
('Михаил Круг'),
('Touch and Go'),
('Lars Bartkuhn'),
('Big Daddy Kane'),
('Kendrick Lamar'),
('Lady Gaga'),
('Hi-Fi Companions'),
('Inner Circle'),
('Hélène Ségara'),
('Elisa Toffoli'),
('The Lady of Rage'),
('Elina Born & Jüri Pootsmann'),
('Prodigy of Mobb Deep'),
('The Avener & John Lee Hooker'),
('Yaki Kadafi'),
('Geri Halliwell'),
('The Last Shadow Puppets'),
('Marvin Gaye'),
('Edvard Grieg'),
('Doğukan Manço'),
('Триагрутрика'),
('Candy Dulfer'),
('Proteus'),
('Calvin Harris'),
('Филипп Киркоров & Николай Басков'),
('Christoph Willibald Gluck'),
('Quest Pistols Show, Slider & Magnit'),
('Rhye'),
('2Pac'),
('C-Funk'),
('Триагрутрика и AK-47'),
('Chic'),
('Gene Henslee'),
('Evanescence'),
('Burial'),
('Don Davis'),
('Milky Chance'),
('KHJ'),
('Сергей Трофимов'),
('Mobb Deep & Wu Tang Clan'),
('a-ha'),
('Dusted'),
('Пикник'),
('Solomon Burke'),
('King Geedorah'),
('Eight Mile Road'),
('Wu-Tang Clan'),
('Joe Strummer & The Mescaleros'),
('Thomas Jack & Jasmine Thompson'),
('Radiohead'),
('Леонид Агутин & Владимир Пресняков-мл.'),
('DOROTHY'),
('Баста & Zivert'),
('John Wasson'),
('Stan Getz'),
('Alex Clare'),
('Moloko'),
('Alekseev'),
('Anne Shelton, The Geoffrey Mitchell Choice & Felton Rapley'),
('The Cranberries'),
('Massive Attack'),
('Jacques Offenbach'),
('Portugal. The Man'),
('Sneaker Pimps'),
('Maroon 5'),
('Грибы'),
('Dirty Hartz'),
('Nacey'),
('Mick Harvey'),
('Hive'),
('2DV'),
('Zero 7'),
('Mark Ronson'),
('Katy Perry'),
('Easy Access Orchestra'),
('Jodeci'),
('VV Brown'),
('Sir Mix-A-Lot'),
('Dirty Vegas'),
('Domu'),
('The Kinks'),
('Broken Back'),
('Lucy Liu & Julie Dreyfus'),
('The Handsome Family'),
('Yan Tregger'),
('HAIM'),
('Creedence Clearwater Revival'),
('Lauren Jauregui'),
('Pearl Jam & Cypress Hill'),
('Ботаника'),
('De La Soul'),
('Tim Simonec'),
('The Satin-Tones'),
('Samuel L. Jackson & John Travolta'),
('Raekwon'),
('Zapp'),
('Би-2'),
('Smif-N-Wessun'),
('Tom Middleton'),
('Yukihiro Fukutomi'),
('Storm'),
('Jason Derulo'),
('Nickelback'),
('Rob Dougan'),
('Rakim'),
('Erick Sermon'),
('Sister Sledge'),
('M&S feat. Jay Ella Ruth'),
('Rick Ross'),
('Craig Mack'),
('Janko Nilovic'),
('Oma Heard'),
('Tom Ze'),
('DJ Puza TGK'),
('Слот'),
('Big L'),
('Adele'),
('Katie Melua'),
('Dropkick Murphys'),
('Toto'),
('G-Unit'),
('Mike & The Modifiers'),
('Alex Attias'),
('Mark The 45 King'),
('O.F.T.B.'),
('Jennifer Jason Leigh'),
('DJ Hurricane'),
('Pillowfight'),
('MC Breed'),
('Idris Muhammad'),
('Free'),
('Grover Washington, Jr.'),
('The Team'),
('Mullyman'),
('Hyenas in the Desert'),
('Lily Allen'),
('Dream Mclean'),
('Louis Armstrong'),
('Dead By Sunrise'),
('The Downbeats'),
('Yukmouth'),
('KMFDM'),
('Don Johnson'),
('Baccara'),
('Eazy-E'),
('Will Smith'),
('Sam & Dave'),
('Poor Righteous Teachers'),
('Slayer & Ice-T'),
('Bob Marley & The Wailers'),
('The Lively Ones'),
('Crazy Baldheads'),
('Supreme Beings of Leisure'),
('Eric B. & Rakim'),
('Kylie Minogue'),
('Gorillaz'),
('St. Germain'),
('Cave'),
('Fussible'),
('Kahuun'),
('The Offspring'),
('Dubmood'),
('Mayer Hawthorne'),
('DJ Quik'),
('Rev. Columbus Mann'),
('Knoc-Turn''al'),
('The Serenaders'),
('Carol Williams'),
('Hole'),
('Atmosphere'),
('Emphasis'),
('Santa Esmeralda'),
('Jacki-O'),
('Vibe TGK'),
('Bruce Willis'),
('Eric B & Rakim'),
('Angie Martinez'),
('The Herbaliser'),
('Shawn Lee'),
('Samuel L. Jackson, Demián Bichir & Walton Goggins'),
('Young Lay'),
('Elvis Presley'),
('José Feliciano'),
('Justin Timberlake'),
('Forces of Nature'),
('Digital Underground'),
('Boyz N Da Hood'),
('Dave King'),
('Little Otis'),
('Макс Барских'),
('Marty Mcfly With the Starlighters'),
('Bone Thugs-N-Harmony'),
('Boyz II Men'),
('Hil St. Soul'),
('Gene Autry'),
('The RZA & Charles Bernstein'),
('Bossman'),
('Элджей'),
('GZA'),
('Hochii'),
('Lee Fields'),
('Al Hirt'),
('Jennifer Jason Leigh, Kurt Russell & Samuel L. Jackson'),
('Faith No More & Boo-Yaa T.R.I.B.E.'),
('Poison'),
('Danny Kaye, Bing Crosby, Peggy Lee & Trudy Stevens'),
('Lil'' Kim'),
('Ian Pooley'),
('Запрещённые барабанщики'),
('Luis Fonsi'),
('Цветы'),
('Richard Wagner'),
('Y?N-Vee'),
('Marshmello & Kane Brown'),
('Mick Jagger'),
('Ryan Gosling & Emma Stone'),
('Andre Williams'),
('Synapson'),
('Wolfgang Amadeus Mozart'),
('Foreign Beggars'),
('American Relay'),
('Adina Howard'),
('Domino'),
('Childish Gambino'),
('The White Stripes'),
('Scott Grooves'),
('Tennis'),
('Pink Martini'),
('Nutt-So'),
('Skye'),
('Jennifer Lopez'),
('Brenda Holloway'),
('I Cantori Moderni di Alessandroni'),
('Clean Bandit'),
('Demi Lovato'),
('Valerie June'),
('The Four Tops'),
('Juno Reactor & Don Davis'),
('Front Line'),
('LSD'),
('Joseph Williams, Sally Dworsky, Nathan Lane, Ernie Sabella & Kristle Edwards'),
('Olivia Newton John'),
('AC/DC'),
('Shorty Long'),
('Anderson .Paak'),
('Kurupt'),
('Frédéric Chopin'),
('Foxes'),
('Mark Mancina'),
('Deltron 3030'),
('Charles Wright & The Watts 103rd Street Rhythm Band'),
('Streetlife'),
('Los Lobos'),
('Don Jagwarr'),
('Fat Joe & Punisher'),
('Mickey McCullers'),
('Стейнбек Джон'),
('Alice Merton'),
('Charles Bradley'),
('Big Cheese All Stars'),
('Mobb Deep'),
('Whodini'),
('The Creations'),
('Betsy'),
('Highway Superstar'),
('Tim Roth, Walton Goggins & Kurt Russell'),
('Blackbuster'),
('Kadebostany'),
('Kelly Clarkson'),
('Jazmine Sullivan'),
('Lana Del Rey'),
('Bob Seger & the Silver Bullet Band'),
('The Stylers'),
('Eric Clapton'),
('White Zombie'),
('Neu!'),
('Sherri Taylor & Singin'' Sammy Ward'),
('Bonobo'),
('Jamiroquai'),
('Franz Ferdinand'),
('Howard Crockett'),
('Al Green'),
('Bunny Paul'),
('Onyx'),
('Tricky'),
('Lorde'),
('ZAYN'),
('Brenda Lee'),
('The Mighty Mocambos'),
('Freddie Mercury'),
('Naughty By Nature'),
('Kraak & Smaak'),
('Pete Rock & C.L. Smooth'),
('Magnet'),
('Les Baxter and His Orchestra'),
('Run-DMC'),
('Buchanan Brothers'),
('The Wright Specials'),
('Gulsen'),
('Смоки Мо'),
('Sound Effect'),
('CunninLynguists'),
('Digable Planets'),
('Mikael Tariverdiev'),
('Evil Nine'),
('Nazareth'),
('Rage Against The Machine'),
('Big Bad Voodoo Daddy'),
('Alan Silvestri'),
('Alan Reeves, Phil Steele & Philip Brigham'),
('Тимати'),
('Алсу'),
('Frontline'),
('Cool Whip, Tragedy, Freddie Foxxx & Havoc'),
('Mary Wells'),
('Buku'),
('Eddie Fisher'),
('DMX'),
('Lynyrd Skynyrd'),
('Black Thought'),
('Nat "King" Cole'),
('Josef Vobruba Se Svym Orchestrem'),
('M. Ward'),
('Luis Bacalov'),
('Melanie C'),
('Liz Lands & The Voices of Salvation'),
('Jeremy Irons, Whoopi Goldberg, Cheech Marin & Jim Cummings'),
('Warren G'),
('Xzibit'),
('Pharrell Williams'),
('Полина Гагарина'),
('Tech9ne'),
('Земфира'),
('Lucy Dacus'),
('Liz Lands'),
('Карандаш'),
('Bob Ascroft'),
('Brook Benton'),
('Nicki Minaj'),
('Eagles'),
('Hidden Beach Recordings'),
('Olivia Newton-John'),
('Bristol-Myers'),
('Paul Revere & The Raiders'),
('Willy Northpole'),
('Леонид Агутин'),
('Jonell & Method Man'),
('Eartha Kitt'),
('Hyper vs. The Crystal Method'),
('Imany'),
('Snoop Жаба Жаб'),
('Bee Gees'),
('Avril Lavigne'),
('DJ Vapour'),
('Елена Темникова'),
('Peggy Lee'),
('ponyhafnium'),
('S.B.H. Project'),
('Half Moon Run'),
('The Donnas'),
('Johnny Kidd & The Pirates'),
('Lenin & Карандаш'),
('12th Planet & SPL'),
('Fergie'),
('The Gospel Stars'),
('T.I.'),
('Manor Boys'),
('Flipsyde'),
('Carmen Twillie & Lebo M.'),
('Nate Dogg'),
('David A. Stewart & Candy Dulfer'),
('Time Zone'),
('The Sugarhill Gang'),
('2Pac & The Outlawz'),
('Michael Giacchino'),
('VIP'),
('Clever Jeff'),
('Amy Winehouse'),
('David Guetta'),
('Run D.M.C. vs. Jason Nevins'),
('Gustav Mahler'),
('Steve Smith'),
('Emancipator'),
('Big Boi'),
('Elsiane'),
('Madvillain'),
('Ofenbach'),
('OutKast'),
('Dickie Valentine'),
('John Mellencamp'),
('The Manor Boys'),
('Gwen Stefani'),
('J Dilla'),
('Alessio Santoni'),
('Smokey Robinson & The Miracles'),
('Riziero Ortolani'),
('The Pharcyde'),
('Dexter Wansel'),
('Don Henley'),
('Poets of the Fall'),
('Christina Aguilera'),
('Сергей Шнуров'),
('Pain'),
('Portishead'),
('Obie Trice'),
('Grace Potter & The Nocturnals'),
('Das EFX'),
('Sabrepulse'),
('Doctor Rockit'),
('Nirvana'),
('The Black Seeds'),
('Ray Charles'),
('Bondage Fairies'),
('The Village Callers'),
('Paula Greer'),
('Sheryl Crow'),
('Marc Streitenfeld'),
('Daft Punk'),
('Natalie Imbruglia'),
('Bei Bei & Shawn Lee'),
('Ray Oddis'),
('Dibia$e'),
('Drake'),
('Snoop Dogg'),
('S-X'),
('Sonny Boy Williamson'),
('Кипелов'),
('The Rembrandts'),
('Xscape'),
('Carmine Coppola & Nino Rota'),
('Walton Goggins, Jennifer Jason Leigh & Michael Madsen'),
('Nina Simone'),
('Quest Pistols Show'),
('Imagine Dragons'),
('Marley Marl'),
('Ани Лорак'),
('Филипп Киркоров'),
('Billy Merritt'),
('Ayro'),
('FLEECE'),
('The Supremes'),
('Teddy Pendergrass'),
('The Andantes'),
('John Travolta & Olivia Newton-John'),
('Marilyn Manson'),
('Louis Prima'),
('Audio Bullys'),
('The Silver Seas'),
('Vera Lynn'),
('Sophie Ellis-Bextor'),
('Dennis Edwards'),
('Guns N'' Roses'),
('Lole y Manuel'),
('Jules Massenet'),
('Monster Magnet'),
('Hank & Carol Diamond'),
('Lostprophets'),
('Vibe TGK & Taj Mahal'),
('Vangelis'),
('Sufjan Stevens'),
('Neil Diamond'),
('DeBarge'),
('Stockard Channing'),
('Hird'),
('Merry Clayton'),
('P. Diddy'),
('Joe Cocker'),
('The Get'' Em Mamis'),
('Bing Crosby'),
('DJ Revolution'),
('Dave Matthews Band'),
('Malcolm McLaren'),
('The Darnells'),
('Original Tropicana Steel Band'),
('Dr. John'),
('Elisabeth Schumann'),
('Leonard Cohen'),
('DJ Shadow'),
('The Avener & Kadebostany'),
('The Super Phonics'),
('Helen St. John'),
('Shakira'),
('Living Colour'),
('Gustavo Santaolalla'),
('Децл'),
('Flux Pavilion'),
('Flosstradamus'),
('Enigma'),
('Hank Levy'),
('Chico Leverett'),
('The Cardigans'),
('Thelonious Monk'),
('Amel Bent'),
('Vitamin String Quartet'),
('Yvette Michelle'),
('Christoph Waltz'),
('Alicia Keys'),
('Marina & The Diamonds'),
('La Roux'),
('Aloe Blacc')
;